<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.8.26">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">

<meta name="author" content="Jonathan Wilson">
<meta name="author" content="Chujiang (CJ) Wu">
<meta name="dcterms.date" content="2026-10-04">

<title>Blocked: Autonomous-Vehicle Blocking Incidents in San Francisco – AV Blocking Incidents</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for citations */
div.csl-bib-body { }
div.csl-entry {
  clear: both;
  margin-bottom: 0em;
}
.hanging-indent div.csl-entry {
  margin-left:2em;
  text-indent:-2em;
}
div.csl-left-margin {
  min-width:2em;
  float:left;
}
div.csl-right-inline {
  margin-left:2em;
  padding-left:1em;
}
div.csl-indent {
  margin-left: 2em;
}</style>


<script src="site_libs/quarto-nav/quarto-nav.js"></script>
<script src="site_libs/quarto-nav/headroom.min.js"></script>
<script src="site_libs/clipboard/clipboard.min.js"></script>
<script src="site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="site_libs/quarto-search/fuse.min.js"></script>
<script src="site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="./">
<script src="site_libs/quarto-html/quarto.js" type="module"></script>
<script src="site_libs/quarto-html/tabsets/tabsets.js" type="module"></script>
<script src="site_libs/quarto-html/axe/axe-check.js" type="module"></script>
<script src="site_libs/quarto-html/popper.min.js"></script>
<script src="site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="site_libs/quarto-html/anchor.min.js"></script>
<link href="site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="site_libs/quarto-html/quarto-syntax-highlighting-587c61ba64f3a5504c4d52d930310e48.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="site_libs/bootstrap/bootstrap.min.js"></script>
<link href="site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="site_libs/bootstrap/bootstrap-ceaa104d35ef12004d771d89dac4dd97.min.css" rel="stylesheet" append-hash="true" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "location": "navbar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "end",
  "type": "overlay",
  "limit": 50,
  "keyboard-shortcut": [
    "f",
    "/",
    "s"
  ],
  "show-item-context": false,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-text-placeholder": "",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit",
    "search-label": "Search"
  }
}</script>

  <script src="https://cdnjs.cloudflare.com/polyfill/v3/polyfill.min.js?features=es6"></script>
  <script src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js" type="text/javascript"></script>

<script type="text/javascript">
const typesetMath = (el) => {
  if (window.MathJax) {
    // MathJax Typeset
    window.MathJax.typeset([el]);
  } else if (window.katex) {
    // KaTeX Render
    var mathElements = el.getElementsByClassName("math");
    var macros = [];
    for (var i = 0; i < mathElements.length; i++) {
      var texText = mathElements[i].firstChild;
      if (mathElements[i].tagName == "SPAN" && texText && texText.data) {
        window.katex.render(texText.data, mathElements[i], {
          displayMode: mathElements[i].classList.contains('display'),
          throwOnError: false,
          macros: macros,
          fleqn: false
        });
      }
    }
  }
}
window.Quarto = {
  typesetMath
};
</script>

<link rel="stylesheet" href="styles.css">
</head>

<body class="nav-fixed quarto-light">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
    <nav class="navbar navbar-expand-lg " data-bs-theme="dark">
      <div class="navbar-container container-fluid">
      <div class="navbar-brand-container mx-auto">
    <a class="navbar-brand" href="./index.html">
    <span class="navbar-title">AV Blocking Incidents</span>
    </a>
  </div>
            <div id="quarto-search" class="" title="Search"></div>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse" aria-controls="navbarCollapse" role="menu" aria-expanded="false" aria-label="Toggle navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
  <span class="navbar-toggler-icon"></span>
</button>
          <div class="collapse navbar-collapse" id="navbarCollapse">
            <ul class="navbar-nav navbar-nav-scroll me-auto">
  <li class="nav-item">
    <a class="nav-link" href="./index.html"> 
<span class="menu-text">Home</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link active" href="./paper.html" aria-current="page"> 
<span class="menu-text">Paper</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="./paper-slides.html"> 
<span class="menu-text">Slides</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="./notebook.html"> 
<span class="menu-text">Notebook</span></a>
  </li>  
</ul>
            <ul class="navbar-nav navbar-nav-scroll ms-auto">
  <li class="nav-item compact">
    <a class="nav-link" href="https://github.com/jonathanwilsonami/av-blocking-analysis"> <i class="bi bi-github" role="img">
</i> 
<span class="menu-text"></span></a>
  </li>  
</ul>
          </div> <!-- /navcollapse -->
            <div class="quarto-navbar-tools">
</div>
      </div> <!-- /container-fluid -->
    </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article page-navbar">
<!-- sidebar -->
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">On this page</h2>
   
  <ul>
  <li><a href="#introduction" id="toc-introduction" class="nav-link active" data-scroll-target="#introduction"><span class="header-section-number">1</span> Introduction</a></li>
  <li><a href="#data" id="toc-data" class="nav-link" data-scroll-target="#data"><span class="header-section-number">2</span> Data</a>
  <ul class="collapse">
  <li><a href="#source-and-cleaning" id="toc-source-and-cleaning" class="nav-link" data-scroll-target="#source-and-cleaning"><span class="header-section-number">2.1</span> Source and cleaning</a></li>
  <li><a href="#secondary-sheets-and-data-engineering" id="toc-secondary-sheets-and-data-engineering" class="nav-link" data-scroll-target="#secondary-sheets-and-data-engineering"><span class="header-section-number">2.2</span> Secondary sheets and data engineering</a></li>
  </ul></li>
  <li><a href="#hazard-taxonomy-and-narrative-classification" id="toc-hazard-taxonomy-and-narrative-classification" class="nav-link" data-scroll-target="#hazard-taxonomy-and-narrative-classification"><span class="header-section-number">3</span> Hazard taxonomy and narrative classification</a>
  <ul class="collapse">
  <li><a href="#design-principles" id="toc-design-principles" class="nav-link" data-scroll-target="#design-principles"><span class="header-section-number">3.1</span> Design principles</a></li>
  <li><a href="#sec-classification" id="toc-sec-classification" class="nav-link" data-scroll-target="#sec-classification"><span class="header-section-number">3.2</span> Classification method</a></li>
  <li><a href="#contributing-causes" id="toc-contributing-causes" class="nav-link" data-scroll-target="#contributing-causes"><span class="header-section-number">3.3</span> Contributing causes</a></li>
  </ul></li>
  <li><a href="#sec-impact" id="toc-sec-impact" class="nav-link" data-scroll-target="#sec-impact"><span class="header-section-number">4</span> Impact scoring</a></li>
  <li><a href="#sec-frequency" id="toc-sec-frequency" class="nav-link" data-scroll-target="#sec-frequency"><span class="header-section-number">5</span> Frequency estimation</a>
  <ul class="collapse">
  <li><a href="#model" id="toc-model" class="nav-link" data-scroll-target="#model"><span class="header-section-number">5.1</span> Model</a></li>
  <li><a href="#results" id="toc-results" class="nav-link" data-scroll-target="#results"><span class="header-section-number">5.2</span> Results</a></li>
  </ul></li>
  <li><a href="#sec-trends" id="toc-sec-trends" class="nav-link" data-scroll-target="#sec-trends"><span class="header-section-number">6</span> Is anything changing over time?</a>
  <ul class="collapse">
  <li><a href="#choosing-the-tests" id="toc-choosing-the-tests" class="nav-link" data-scroll-target="#choosing-the-tests"><span class="header-section-number">6.1</span> Choosing the tests</a></li>
  <li><a href="#incident-counts-and-durations" id="toc-incident-counts-and-durations" class="nav-link" data-scroll-target="#incident-counts-and-durations"><span class="header-section-number">6.2</span> Incident counts and durations</a></li>
  <li><a href="#sec-mix" id="toc-sec-mix" class="nav-link" data-scroll-target="#sec-mix"><span class="header-section-number">6.3</span> The hazard mix shift is a reporting artifact</a></li>
  </ul></li>
  <li><a href="#sec-risk" id="toc-sec-risk" class="nav-link" data-scroll-target="#sec-risk"><span class="header-section-number">7</span> Risk matrix</a>
  <ul class="collapse">
  <li><a href="#probability-and-impact-bands" id="toc-probability-and-impact-bands" class="nav-link" data-scroll-target="#probability-and-impact-bands"><span class="header-section-number">7.1</span> Probability and impact bands</a></li>
  <li><a href="#risk-curve-placement" id="toc-risk-curve-placement" class="nav-link" data-scroll-target="#risk-curve-placement"><span class="header-section-number">7.2</span> Risk-curve placement</a></li>
  <li><a href="#why-each-hazard-sits-where-it-does" id="toc-why-each-hazard-sits-where-it-does" class="nav-link" data-scroll-target="#why-each-hazard-sits-where-it-does"><span class="header-section-number">7.3</span> Why each hazard sits where it does</a></li>
  </ul></li>
  <li><a href="#sec-sensitivity" id="toc-sec-sensitivity" class="nav-link" data-scroll-target="#sec-sensitivity"><span class="header-section-number">8</span> Sensitivity analysis</a></li>
  <li><a href="#discussion-and-limitations" id="toc-discussion-and-limitations" class="nav-link" data-scroll-target="#discussion-and-limitations"><span class="header-section-number">9</span> Discussion and limitations</a>
  <ul class="collapse">
  <li><a href="#sec-judgment" id="toc-sec-judgment" class="nav-link" data-scroll-target="#sec-judgment"><span class="header-section-number">9.1</span> What is measured and what is judged</a></li>
  <li><a href="#limitations" id="toc-limitations" class="nav-link" data-scroll-target="#limitations"><span class="header-section-number">9.2</span> Limitations</a></li>
  </ul></li>
  <li><a href="#conclusions" id="toc-conclusions" class="nav-link" data-scroll-target="#conclusions"><span class="header-section-number">10</span> Conclusions</a></li>
  <li><a href="#acknowledgments" id="toc-acknowledgments" class="nav-link" data-scroll-target="#acknowledgments">Acknowledgments</a></li>
  <li><a href="#references" id="toc-references" class="nav-link" data-scroll-target="#references">References</a></li>
  </ul>
<div class="toc-actions"><ul><li><a href="https://github.com/jonathanwilsonami/av-blocking-analysis/blob/main/paper.qmd" class="toc-action"><i class="bi bi-github"></i>View source</a></li><li><a href="https://github.com/jonathanwilsonami/av-blocking-analysis/issues/new" class="toc-action"><i class="bi empty"></i>Report an issue</a></li></ul></div><div class="quarto-alternate-formats"><h2>Other Formats</h2><ul><li><a href="paper-slides.html"><i class="bi bi-file-slides"></i>RevealJS</a></li></ul></div></nav>
    </div>
<!-- main -->
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title">Blocked: Autonomous-Vehicle Blocking Incidents in San Francisco</h1>
<p class="subtitle lead">Frequency, hazard classification, and risk-matrix placement from the 2025 DEM incident log</p>
</div>



<div class="quarto-title-meta">

    <div>
    <div class="quarto-title-meta-heading">Authors</div>
    <div class="quarto-title-meta-contents">
             <p>Jonathan Wilson </p>
             <p>Chujiang (CJ) Wu </p>
          </div>
  </div>
    
    <div>
    <div class="quarto-title-meta-heading">Published</div>
    <div class="quarto-title-meta-contents">
      <p class="date">October 4, 2026</p>
    </div>
  </div>
  
    
  </div>
  
<div>
  <div class="abstract">
    <div class="block-title">Abstract</div>
    <p>Robotaxis that become immobilized in the roadway can obstruct general traffic, public transit, pedestrians, and emergency responders. We analyze the 123 AV blocking incidents recorded by the San Francisco Department of Emergency Management (DEM) between February 1, 2025 and October 31, 2025. We design a consequence-based hazard taxonomy and classify each narrative with a transparent rule set, which we compare against supervised models, two zero-shot transformers, and an embedding-similarity baseline. A blind LLM second coder serves as a cross-check (Cohen’s <span class="math inline">\(\kappa\)</span> = 0.95 with the manual audit). Frequencies are estimated with Poisson and Jeffreys-Bayesian models. Change over time is tested with non-parametric methods suited to six monthly counts and heavily skewed durations. Each hazard is placed on a 5×5 likelihood–consequence matrix with a “risk-curve” rule that pairs each consequence level with its own frequency. Blocking incidents occur about 19.6 times per 30 days, with no statistically detectable trend in rate or duration. AV-involved collisions, emergency-response obstruction, and routine single-AV lane blockages rank highest (<em>Very high</em>). Transit obstruction and multi-AV gridlock are <em>High</em>. Pedestrian/accessibility and occupant-related hazards are <em>Medium</em>.</p>
  </div>
</div>


</header>


<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Note</span>Reproducibility and data credit
</div>
</div>
<div class="callout-body-container callout-body">
<p>Every number, figure, and table in this paper is produced by <code>notebooks/av_blocking_analysis.ipynb</code> and exported to <code>project-site/assets/</code>. Inline numbers are read from <code>_variables.yml</code>, so re-running the notebook updates the paper. The incident records come from the San Francisco Department of Emergency Management. <strong>Most of the difficult original data cleaning was performed by Dr.&nbsp;Missy Cummings</strong>, and this analysis builds directly on that work.</p>
</div>
</div>
<section id="introduction" class="level1" data-number="1">
<h1 data-number="1"><span class="header-section-number">1</span> Introduction</h1>
<p>Driverless ride-hail fleets now operate at scale in San Francisco. When an AV cannot resolve a situation, the safe default is to stop and wait for remote assistance or a field technician. That situation might be an unusual intersection geometry, a dark traffic signal, an emergency scene, a passenger who will not leave, or a software or hardware fault. A stopped vehicle is safe for its occupants but not necessarily for everyone else: it can block lanes, transit, crosswalks, and emergency apparatus, often for long stretches. City agencies record these events as <strong>blocking incidents</strong>.</p>
<p>This paper asks three questions of the DEM blocking-incident log:</p>
<ol type="1">
<li><strong>Frequency.</strong> How often do blocking incidents, and each kind of hazard they create, occur, and how uncertain are those estimates?</li>
<li><strong>Hazard classification.</strong> What hazards do these incidents create, and how can free-text dispatcher narratives be classified into them defensibly?</li>
<li><strong>Risk.</strong> Where does each hazard sit on a standard 5×5 red/yellow/green risk matrix, and is anything changing over time?</li>
</ol>
<p>The emphasis throughout is on conclusions that are statistically defensible given a small, irregular, and imperfect sample. Several steps also require judgment, such as how hazards are defined and how severe an hour-long blockage is. <a href="#sec-judgment" class="quarto-xref">Section&nbsp;9.1</a> separates what is measured from what is judged.</p>
</section>
<section id="data" class="level1" data-number="2">
<h1 data-number="2"><span class="header-section-number">2</span> Data</h1>
<section id="source-and-cleaning" class="level2" data-number="2.1">
<h2 data-number="2.1" class="anchored" data-anchor-id="source-and-cleaning"><span class="header-section-number">2.1</span> Source and cleaning</h2>
<p>The primary source is the <code>DEM Incidents</code> sheet of <code>AV-Brick-Report.xlsx</code>. Each record has a date, location, free-text dispatcher narrative, number of AVs involved, and the times the event started and cleared. The records originate with the San Francisco Department of Emergency Management. Dr.&nbsp;Missy Cummings compiled and cleaned them from raw dispatch records, which was the hard part.</p>
<p>We apply light, documented cleaning (<a href="#tbl-data-quality" class="quarto-xref">Table&nbsp;1</a>):</p>
<ul>
<li>parse the mixed time formats;</li>
<li>compute duration as clear minus start, modulo 1,440 minutes, so events crossing midnight are handled;</li>
<li>flag missing and truncated narratives;</li>
<li>extract the operator;</li>
<li>treat a missing AV count as at least one.</li>
</ul>
<div id="tbl-data-quality" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-tbl figure">
<figcaption class="quarto-float-caption-top quarto-float-caption quarto-float-tbl" id="tbl-data-quality-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Table&nbsp;1: Data inventory and quality checks for the primary DEM sheet.
</figcaption>
<div aria-describedby="tbl-data-quality-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<table class="caption-top table">
<colgroup>
<col style="width: 36%">
<col style="width: 63%">
</colgroup>
<thead>
<tr class="header">
<th style="text-align: left;">Quantity</th>
<th style="text-align: left;">Value</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">Incidents (primary sheet)</td>
<td style="text-align: left;">123</td>
</tr>
<tr class="even">
<td style="text-align: left;">Date range</td>
<td style="text-align: left;">2025-02-01 to 2025-10-31</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Months present</td>
<td style="text-align: left;">2025-02, 2025-03, 2025-06, 2025-07, 2025-08, 2025-09, 2025-10</td>
</tr>
<tr class="even">
<td style="text-align: left;">Covered months used for rates</td>
<td style="text-align: left;">2025-03, 2025-06, 2025-07, 2025-08, 2025-09, 2025-10</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Covered exposure (days)</td>
<td style="text-align: left;">184</td>
</tr>
<tr class="even">
<td style="text-align: left;">Incidents in covered months</td>
<td style="text-align: left;">120</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Narrative missing</td>
<td style="text-align: left;">1</td>
</tr>
<tr class="even">
<td style="text-align: left;">Narrative likely truncated</td>
<td style="text-align: left;">83 (67%)</td>
</tr>
<tr class="odd">
<td style="text-align: left;">AV count missing</td>
<td style="text-align: left;">3</td>
</tr>
<tr class="even">
<td style="text-align: left;">Durations crossing midnight</td>
<td style="text-align: left;">3</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Operator = Waymo / Zoox / unstated</td>
<td style="text-align: left;">110 / 1 / 12</td>
</tr>
</tbody>
</table>
</div>
</figure>
</div>
<p><strong>Narrative truncation.</strong> 67% of narratives (83 of 123) appear to have been cut at about 45–60 characters by the export. This limits what any text classifier can recover, and it turns out to matter for the trend analysis (<a href="#sec-mix" class="quarto-xref">Section&nbsp;6.3</a>).</p>
<p><strong>Coverage.</strong> The log is not continuous. February holds only three incidents, all on its first three days, and April and May are absent. Treating absent months as zero-incident months would bias every rate and trend estimate. All rates and trend tests therefore use the 6 fully covered months (March and June–October: 184 days, 120 incidents). The February incidents still count toward hazard classification and impact scoring. <a href="#sec-sensitivity" class="quarto-xref">Section&nbsp;8</a> shows that the conclusions do not change if February is included.</p>
</section>
<section id="secondary-sheets-and-data-engineering" class="level2" data-number="2.2">
<h2 data-number="2.2" class="anchored" data-anchor-id="secondary-sheets-and-data-engineering"><span class="header-section-number">2.2</span> Secondary sheets and data engineering</h2>
<p>The analyzed workbook (<code>AV-Brick-Report-analyzed.xlsx</code>) contributes four things:</p>
<ul>
<li><strong>Extra fields.</strong> The AV company’s ETA (given for 22 incidents; median 14.5 minutes), other parties involved, and emergency-responder and transit-impact flags. These are joined on date and location, and all 123 primary rows match.</li>
<li><strong>A neighborhood zone (1–10)</strong> hand-coded in <code>DEM Incidents Quant</code> (119 of 123 match). The same sheet’s derived flags (multi-AV, 4-hour time-of-day bin, &gt;20 / &gt;40-minute durations) are recomputed from source fields.</li>
<li><strong>8 additional incidents</strong> that have narratives but no times. They are excluded from duration analysis but used in a frequency sensitivity check.</li>
<li><strong>The <code>plots and stats</code> sheet.</strong> Monthly duration summaries, a six-group normality/rank-sum table, and a March-vs-October Mann–Whitney test (W = 377, p = 0.063). We replicate this result and extend it in <a href="#sec-trends" class="quarto-xref">Section&nbsp;6</a>.</li>
</ul>
<p>The analyzed sheet’s emergency-responder flag marks <em>responder involvement</em>, for example police called to direct traffic around a stalled AV. It does not mark obstruction of an emergency, so it is kept as a feature and does not define a hazard.</p>
</section>
</section>
<section id="hazard-taxonomy-and-narrative-classification" class="level1" data-number="3">
<h1 data-number="3"><span class="header-section-number">3</span> Hazard taxonomy and narrative classification</h1>
<section id="design-principles" class="level2" data-number="3.1">
<h2 data-number="3.1" class="anchored" data-anchor-id="design-principles"><span class="header-section-number">3.1</span> Design principles</h2>
<p>A hazard is defined by its <strong>consequence</strong>: what the immobilized AV obstructed or put at risk. Two design rules make the classes defensible.</p>
<ol type="1">
<li><strong>Consequence and cause are separate axes.</strong> <em>Why</em> the AV stopped (a vehicle fault, a dark signal, a passenger, a routing edge case) is recorded separately as a contributing cause. Ad-hoc incident codes often mix the two, producing overlapping categories whose frequencies cannot be compared.</li>
<li><strong>Mutually exclusive and exhaustive, by precedence.</strong> An incident can match several descriptions, for example two AVs stuck at a working fire. Each incident takes the <em>most severe</em> class it matches, in the order H1 &gt; H2 &gt; … &gt; H7, with H7 as the default. Every incident therefore counts exactly once, and frequencies add up to the total.</li>
</ol>
<p>H6 (multi-AV clustering) is a class of its own because several AVs failing together at one site signals a <strong>common-mode, fleet-level failure</strong>, a mechanism distinct from one vehicle’s fault. It also takes a disproportionate share of road capacity. Single events in the log involve up to 60 vehicles.</p>
<div id="tbl-taxonomy" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-tbl figure">
<figcaption class="quarto-float-caption-top quarto-float-caption quarto-float-tbl" id="tbl-taxonomy-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Table&nbsp;2: Consequence-based hazard taxonomy (assigned by severity-first precedence).
</figcaption>
<div aria-describedby="tbl-taxonomy-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<table class="caption-top table">
<colgroup>
<col style="width: 3%">
<col style="width: 19%">
<col style="width: 76%">
</colgroup>
<thead>
<tr class="header">
<th style="text-align: left;">Code</th>
<th style="text-align: left;">Hazard</th>
<th style="text-align: left;">Definition</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">H1</td>
<td style="text-align: left;">AV-involved collision</td>
<td style="text-align: left;">The AV made (or was reported to make) contact with another road user, vehicle, or animal, leaving the AV or the scene blocking the roadway.</td>
</tr>
<tr class="even">
<td style="text-align: left;">H2</td>
<td style="text-align: left;">Emergency-response obstruction</td>
<td style="text-align: left;">The AV obstructed an emergency response (medics, fire, police) or became stuck inside an active emergency scene (fire, crash scene, police investigation).</td>
</tr>
<tr class="odd">
<td style="text-align: left;">H3</td>
<td style="text-align: left;">Transit / rail obstruction</td>
<td style="text-align: left;">The AV blocked a public-transit vehicle, lane, or track (Muni bus or rail, cable car) or a railroad track.</td>
</tr>
<tr class="even">
<td style="text-align: left;">H4</td>
<td style="text-align: left;">Pedestrian / accessibility obstruction</td>
<td style="text-align: left;">The AV blocked a crosswalk, curb ramp, or bike lane, pushing vulnerable road users into traffic.</td>
</tr>
<tr class="odd">
<td style="text-align: left;">H5</td>
<td style="text-align: left;">Occupant-related immobilization</td>
<td style="text-align: left;">A passenger condition or action immobilized the AV: unresponsive/asleep rider, occupant trapped or calling for help, or a door left open.</td>
</tr>
<tr class="even">
<td style="text-align: left;">H6</td>
<td style="text-align: left;">Multi-AV clustering / gridlock</td>
<td style="text-align: left;">Two or more AVs immobilized together at one location (a common-mode, fleet-level failure) with none of the above consequences.</td>
</tr>
<tr class="odd">
<td style="text-align: left;">H7</td>
<td style="text-align: left;">Single-AV traffic obstruction</td>
<td style="text-align: left;">One AV stalled in a travel lane, intersection, or roadway, obstructing general traffic only. Default class.</td>
</tr>
</tbody>
</table>
</div>
</figure>
</div>
</section>
<section id="sec-classification" class="level2" data-number="3.2">
<h2 data-number="3.2" class="anchored" data-anchor-id="sec-classification"><span class="header-section-number">3.2</span> Classification method</h2>
<p>Choosing a classifier is a question of fit to the data. The data here are 123 short, often truncated narratives written in dispatcher shorthand (<code>blkng</code>, <code>ntfyd</code>, <code>LP</code>). There are no gold-standard labels, and the safety-relevant classes have only 4–9 examples. We compared five families of approach:</p>
<ul>
<li><strong>Transparent rules</strong>: keyword and regular-expression patterns plus the AV-count field, implemented in <code>av_blocking.taxonomy</code>.</li>
<li><strong>Supervised TF-IDF models</strong>: word and character n-grams with multinomial logistic regression, and with XGBoost <span class="citation" data-cites="chen2016">(<a href="#ref-chen2016" role="doc-biblioref">Chen and Guestrin 2016</a>)</span>.</li>
<li><strong>Zero-shot NLI transformers</strong> <span class="citation" data-cites="yin2019">(<a href="#ref-yin2019" role="doc-biblioref">Yin, Hay, and Roth 2019</a>)</span>: BART-large-MNLI <span class="citation" data-cites="lewis2020">(<a href="#ref-lewis2020" role="doc-biblioref">Lewis et al. 2020</a>)</span> and a DeBERTa-v3-large model fine-tuned on several NLI datasets <span class="citation" data-cites="he2023 laurer2024">(<a href="#ref-he2023" role="doc-biblioref">He, Gao, and Chen 2023</a>; <a href="#ref-laurer2024" role="doc-biblioref">Laurer et al. 2024</a>)</span>. Each plain-language hazard description becomes the hypothesis “This incident report describes {description}”, and the model scores how strongly the narrative entails it.</li>
<li><strong>Embedding similarity</strong>: a sentence-embedding model (mxbai-embed-large <span class="citation" data-cites="mxbai2024">(<a href="#ref-mxbai2024" role="doc-biblioref">Mixedbread AI 2024</a>)</span>; see <span class="citation" data-cites="reimers2019">Reimers and Gurevych (<a href="#ref-reimers2019" role="doc-biblioref">2019</a>)</span> for the approach) embeds each narrative and each hazard description, and the most similar description (cosine similarity) wins.</li>
<li><strong>Majority-class baseline.</strong></li>
</ul>
<p>All three pretrained models use the <em>same</em> six hazard descriptions and see no labeled examples from this log. Each was run once on CPU, and its predictions are cached in <code>data/processed/</code>.</p>
<p>Fine-tuning a transformer was not attempted. With so few examples it would overfit, and the result could not be audited.</p>
<p>As a reference, every narrative was read and hand-coded, with notes on ambiguous cases (<code>data/labels/manual_hazard_labels.csv</code>). Agreement between the rules and the manual labels is 99.2% (Cohen’s <span class="math inline">\(\kappa\)</span> = 0.99) <span class="citation" data-cites="cohen1960">(<a href="#ref-cohen1960" role="doc-biblioref">Cohen 1960</a>)</span>, where</p>
<p><span class="math display">\[
\kappa = \frac{p_o - p_e}{1 - p_e},
\]</span></p>
<p><span class="math inline">\(p_o\)</span> is the observed agreement and <span class="math inline">\(p_e\)</span> the agreement expected by chance from the label margins. The rules were written by the same analyst who made the reference labels, so this figure is an internal-consistency check, not an independent validation. The one remaining disagreement is a genuinely ambiguous crash scene (<a href="#tbl-disagreements" class="quarto-xref">Table&nbsp;9</a>).</p>
<p><strong>Blind second coder.</strong> To address the single-analyst problem, a second coder from a different model family labeled all 123 incidents <em>blind</em>: OpenAI’s Codex (based on GPT-6; the exact build is not exposed). It received only a label-free packet (<code>data/labels/blind_audit/</code>): the narratives and AV counts, plus a coding guide with the seven definitions, the precedence and AV-count rules, and a glossary of dispatcher shorthand. The guide contained no worked examples. Codex reported opening no other file, and the repository confirms it modified nothing else. It was told to judge each narrative itself rather than use keyword scripts, and to give a confidence level and rationale per incident.</p>
<p>It agreed with the manual audit on 119 of 123 incidents (<span class="math inline">\(\kappa\)</span> = 0.95) and with the rules on 120 (<span class="math inline">\(\kappa\)</span> = 0.96). Fleiss’ <span class="math inline">\(\kappa\)</span> across all three coders is 0.965 (<a href="#tbl-coder-agreement" class="quarto-xref">Table&nbsp;3</a>). The 4 disagreements share one pattern: Codex read truncated narratives more literally, declining to infer a transit or occupant consequence that the visible text does not state. It flagged 3 of them as low confidence itself (<a href="#tbl-coder-disagreements" class="quarto-xref">Table&nbsp;4</a>). On review, every disagreement is a defensible judgment call either way, so the labels and rules were kept unchanged. Because this is a <em>language-model</em> second coder, the agreement is evidence that the taxonomy can be applied consistently from its written definitions. It is not a substitute for human inter-rater reliability: two language models may share biases from training.</p>
<div id="tbl-coder-agreement" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-tbl figure">
<figcaption class="quarto-float-caption-top quarto-float-caption quarto-float-tbl" id="tbl-coder-agreement-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Table&nbsp;3: Inter-coder agreement on hazard labels (n = 123).
</figcaption>
<div aria-describedby="tbl-coder-agreement-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<table class="caption-top table">
<colgroup>
<col style="width: 34%">
<col style="width: 18%">
<col style="width: 12%">
<col style="width: 14%">
<col style="width: 20%">
</colgroup>
<thead>
<tr class="header">
<th style="text-align: left;">Coder A</th>
<th style="text-align: left;">Coder B</th>
<th style="text-align: left;">Agree</th>
<th style="text-align: left;">Percent</th>
<th style="text-align: right;">Cohen kappa</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">LLM second coder (Codex)</td>
<td style="text-align: left;">Manual audit</td>
<td style="text-align: left;">119/123</td>
<td style="text-align: left;">96.7%</td>
<td style="text-align: right;">0.947</td>
</tr>
<tr class="even">
<td style="text-align: left;">LLM second coder (Codex)</td>
<td style="text-align: left;">Rules</td>
<td style="text-align: left;">120/123</td>
<td style="text-align: left;">97.6%</td>
<td style="text-align: right;">0.96</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Manual audit</td>
<td style="text-align: left;">Rules</td>
<td style="text-align: left;">122/123</td>
<td style="text-align: left;">99.2%</td>
<td style="text-align: right;">0.987</td>
</tr>
<tr class="even">
<td style="text-align: left;">All three</td>
<td style="text-align: left;">(Fleiss)</td>
<td style="text-align: left;"></td>
<td style="text-align: left;"></td>
<td style="text-align: right;">0.965</td>
</tr>
</tbody>
</table>
</div>
</figure>
</div>
<div id="tbl-coder-disagreements" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-tbl figure">
<figcaption class="quarto-float-caption-top quarto-float-caption quarto-float-tbl" id="tbl-coder-disagreements-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Table&nbsp;4: Incidents where the LLM second coder disagrees with the manual audit, with its rationale and the resolution.
</figcaption>
<div aria-describedby="tbl-coder-disagreements-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<table class="caption-top table">
<colgroup>
<col style="width: 2%">
<col style="width: 32%">
<col style="width: 2%">
<col style="width: 2%">
<col style="width: 2%">
<col style="width: 4%">
<col style="width: 28%">
<col style="width: 25%">
</colgroup>
<thead>
<tr class="header">
<th style="text-align: left;">Incident</th>
<th style="text-align: left;">Narrative</th>
<th style="text-align: left;">Manual</th>
<th style="text-align: left;">Rules</th>
<th style="text-align: left;">Codex</th>
<th style="text-align: left;">Codex confidence</th>
<th style="text-align: left;">Codex rationale</th>
<th style="text-align: left;">Resolution</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">INC-040</td>
<td style="text-align: left;">Traffic lights are out..hazard for Muni trains..DPT trying</td>
<td style="text-align: left;">H3</td>
<td style="text-align: left;">H3</td>
<td style="text-align: left;">H7</td>
<td style="text-align: left;">low</td>
<td style="text-align: left;">Traffic lights were out and Muni trains faced a hazard, but AV obstruction of transit is not stated.</td>
<td style="text-align: left;">Kept H3. The text does not say the AV blocked transit, but the analyzed sheet’s transit-impact flag is Y.</td>
</tr>
<tr class="even">
<td style="text-align: left;">INC-041</td>
<td style="text-align: left;">Subj inside of a Waymo rtl..AV stationary LP 76962Y3</td>
<td style="text-align: left;">H5</td>
<td style="text-align: left;">H5</td>
<td style="text-align: left;">H7</td>
<td style="text-align: left;">medium</td>
<td style="text-align: left;">A subject was inside a stationary Waymo, but no occupant condition or action causing immobilization is stated.</td>
<td style="text-align: left;">Kept H5. An occupant inside a stopped AV; whether they caused the stop is not stated. Either code is defensible.</td>
</tr>
<tr class="odd">
<td style="text-align: left;">INC-066</td>
<td style="text-align: left;">Traffic hazard due to a veh accident..need PD for traffic control..tow truck en route no eta..PD resp..Waymo able to move AV..no need for PD</td>
<td style="text-align: left;">H1</td>
<td style="text-align: left;">H2</td>
<td style="text-align: left;">H2</td>
<td style="text-align: left;">low</td>
<td style="text-align: left;">A vehicle accident required traffic control, suggesting an active crash scene; the AV relation to that scene is unclear.</td>
<td style="text-align: left;">Kept H1 (manual) / H2 (rules). Already flagged as ambiguous; Codex sided with the rules.</td>
</tr>
<tr class="even">
<td style="text-align: left;">INC-112</td>
<td style="text-align: left;">Waymo is near the railroad track blocking the</td>
<td style="text-align: left;">H3</td>
<td style="text-align: left;">H3</td>
<td style="text-align: left;">H7</td>
<td style="text-align: left;">low</td>
<td style="text-align: left;">The Waymo was near a railroad track and blocking an unspecified object; the truncation does not establish track obstruction.</td>
<td style="text-align: left;">Kept H3. Truncated before saying what was blocked; Codex’s stricter H7 is also defensible.</td>
</tr>
</tbody>
</table>
</div>
</figure>
</div>
<p>The learned models are scored out-of-sample, by 4-fold × 5-repeat stratified cross-validation (<a href="#tbl-classifiers" class="quarto-xref">Table&nbsp;5</a>, <a href="#fig-classifiers" class="quarto-xref">Figure&nbsp;1</a>). They improve only modestly on the majority baseline: macro-F1 0.47 for logistic regression and 0.32 for XGBoost, against 0.25 for the baseline. Logistic regression’s F1 on emergency obstruction is 0, and the rare, high-consequence classes are precisely the ones that drive the risk matrix.</p>
<p>The pretrained models split into two groups (<a href="#tbl-classifiers" class="quarto-xref">Table&nbsp;5</a>, <a href="#tbl-pretrained-counts" class="quarto-xref">Table&nbsp;7</a>):</p>
<ul>
<li><strong>Zero-shot NLI does not help, and a bigger model does not fix it.</strong> BART-large-MNLI reaches macro-F1 0.4. The larger, newer DeBERTa-v3 model does slightly <em>worse</em>, at 0.32, with F1 = 0 on emergency obstruction. The difference from BART is not significant (paired bootstrap ΔF1 = -0.07 (-0.20 to +0.05); McNemar p = 0.064). Both NLI models label about a third of all narratives “collision” (38 and 39 incidents, against 7 in the audit). General-purpose NLI models do not read dispatcher shorthand well, regardless of size.</li>
<li><strong>Embedding similarity is the strongest label-free method.</strong> It reaches macro-F1 0.62, significantly better than BART-MNLI (ΔF1 = +0.22 (+0.08 to +0.36)). It is the only non-rule method with real skill on emergency obstruction (F1 = 0.67). It edges out cross-validated logistic regression, though not significantly (ΔF1 = +0.09 (-0.06 to +0.23); McNemar p = 0.119). Its errors run the other way from NLI: it assigns too many incidents to transit and to pedestrian/accessibility.</li>
<li><strong>A frontier LLM given the written coding guide</strong> is in a different league. Scored the same way, the blind Codex second coder reaches macro-F1 0.95 (<span class="math inline">\(\kappa\)</span> = 0.95), with F1 = 0.92 on emergency obstruction. The deciding factor is the guide (definitions, precedence, shorthand glossary), which the zero-shot models never see, as much as raw model size.</li>
</ul>
<p>The significance tests are paired, because every classifier labels the same incidents (<a href="#tbl-classifier-tests" class="quarto-xref">Table&nbsp;8</a>). The exact McNemar test <span class="citation" data-cites="mcnemar1947">(<a href="#ref-mcnemar1947" role="doc-biblioref">McNemar 1947</a>)</span> uses only the discordant incidents, those one model gets right and the other wrong. With <span class="math inline">\(b\)</span> and <span class="math inline">\(c\)</span> such incidents, under <span class="math inline">\(H_0\)</span>, <span class="math inline">\(b \sim \operatorname{Bin}(b + c, \tfrac12)\)</span>. The macro-F1 difference gets a paired percentile-bootstrap 95% interval <span class="citation" data-cites="efron1993">(<a href="#ref-efron1993" role="doc-biblioref">Efron and Tibshirani 1993</a>)</span> from 5,000 resamples of incidents. Supervised models enter with their out-of-fold predictions.</p>
<p><strong>Choice: the rule set, with the LLM as a cross-check.</strong> A guided frontier LLM labels almost as well as the rules, so the choice is not about raw accuracy. It rests on four properties a hazard classification feeding a risk matrix needs:</p>
<ol type="1">
<li><strong>Auditable.</strong> Every label traces to a named pattern that a reviewer can read and challenge. An LLM’s rationale is a post-hoc explanation, not the mechanism.</li>
<li><strong>Reproducible.</strong> The rules give the same output forever. Hosted LLMs change version silently; Codex could not even report its exact build, so its labels cannot be regenerated bit-for-bit.</li>
<li><strong>Precise where it matters.</strong> The rules encode the severity-first precedence and the AV-count rule exactly, and handle dispatcher shorthand and truncation explicitly.</li>
<li><strong>Cheap and local.</strong> No API cost, no download, and no need to send incident records to a third-party service.</li>
</ol>
<p>The rules’ weakness is generalization: they were written after reading these narratives and may miss phrasings in future logs. The guided LLM is the natural safeguard. Run it on new data, and treat its disagreements with the rules as candidates for review. If the log grows to several hundred incidents, the manual and LLM labels together could train a supervised model.</p>
<div id="tbl-classifiers" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-tbl figure">
<figcaption class="quarto-float-caption-top quarto-float-caption quarto-float-tbl" id="tbl-classifiers-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Table&nbsp;5: Narrative classifiers scored against the manual audit labels (supervised models: mean and SD over 4-fold x 5 repeated stratified CV; pretrained models and the LLM use no training data; the LLM was given the written coding guide).
</figcaption>
<div aria-describedby="tbl-classifiers-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<table class="caption-top table">
<colgroup>
<col style="width: 35%">
<col style="width: 25%">
<col style="width: 10%">
<col style="width: 12%">
<col style="width: 10%">
<col style="width: 7%">
</colgroup>
<thead>
<tr class="header">
<th style="text-align: left;">method</th>
<th style="text-align: left;">family</th>
<th style="text-align: right;">macro_F1</th>
<th style="text-align: left;">macro_F1_sd</th>
<th style="text-align: right;">accuracy</th>
<th style="text-align: right;">kappa</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">Majority class + count rule</td>
<td style="text-align: left;">Baseline</td>
<td style="text-align: right;">0.249</td>
<td style="text-align: left;">—</td>
<td style="text-align: right;">0.724</td>
<td style="text-align: right;">0.433</td>
</tr>
<tr class="even">
<td style="text-align: left;">TF-IDF + XGBoost (CV)</td>
<td style="text-align: left;">Supervised (cross-validated)</td>
<td style="text-align: right;">0.32</td>
<td style="text-align: left;">0.074</td>
<td style="text-align: right;">0.735</td>
<td style="text-align: right;">0.477</td>
</tr>
<tr class="odd">
<td style="text-align: left;">TF-IDF + logistic regression (CV)</td>
<td style="text-align: left;">Supervised (cross-validated)</td>
<td style="text-align: right;">0.47</td>
<td style="text-align: left;">0.085</td>
<td style="text-align: right;">0.774</td>
<td style="text-align: right;">0.582</td>
</tr>
<tr class="even">
<td style="text-align: left;">Zero-shot BART-large-MNLI</td>
<td style="text-align: left;">Pretrained, no training</td>
<td style="text-align: right;">0.396</td>
<td style="text-align: left;">—</td>
<td style="text-align: right;">0.585</td>
<td style="text-align: right;">0.378</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Zero-shot DeBERTa-v3-large NLI</td>
<td style="text-align: left;">Pretrained, no training</td>
<td style="text-align: right;">0.323</td>
<td style="text-align: left;">—</td>
<td style="text-align: right;">0.504</td>
<td style="text-align: right;">0.279</td>
</tr>
<tr class="even">
<td style="text-align: left;">Embedding similarity (mxbai-embed-large)</td>
<td style="text-align: left;">Pretrained, no training</td>
<td style="text-align: right;">0.62</td>
<td style="text-align: left;">—</td>
<td style="text-align: right;">0.691</td>
<td style="text-align: right;">0.563</td>
</tr>
<tr class="odd">
<td style="text-align: left;">LLM + coding guide (Codex, GPT-6-based)</td>
<td style="text-align: left;">LLM with coding guide</td>
<td style="text-align: right;">0.946</td>
<td style="text-align: left;">—</td>
<td style="text-align: right;">0.967</td>
<td style="text-align: right;">0.947</td>
</tr>
<tr class="even">
<td style="text-align: left;">Rule-based (selected; in-sample)</td>
<td style="text-align: left;">Rules</td>
<td style="text-align: right;">0.978</td>
<td style="text-align: left;">—</td>
<td style="text-align: right;">0.992</td>
<td style="text-align: right;">0.987</td>
</tr>
</tbody>
</table>
</div>
</figure>
</div>
<div id="tbl-per-class-f1" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-tbl figure">
<figcaption class="quarto-float-caption-top quarto-float-caption quarto-float-tbl" id="tbl-per-class-f1-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Table&nbsp;6: Per-class F1 by method.
</figcaption>
<div aria-describedby="tbl-per-class-f1-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<table class="caption-top table">
<colgroup>
<col style="width: 10%">
<col style="width: 5%">
<col style="width: 12%">
<col style="width: 7%">
<col style="width: 11%">
<col style="width: 13%">
<col style="width: 17%">
<col style="width: 16%">
<col style="width: 5%">
</colgroup>
<thead>
<tr class="header">
<th style="text-align: left;">Hazard</th>
<th style="text-align: right;">n (manual)</th>
<th style="text-align: right;">TF-IDF + logistic regression</th>
<th style="text-align: right;">TF-IDF + XGBoost</th>
<th style="text-align: right;">Zero-shot BART-large-MNLI</th>
<th style="text-align: right;">Zero-shot DeBERTa-v3-large NLI</th>
<th style="text-align: right;">Embedding similarity (mxbai-embed-large)</th>
<th style="text-align: right;">LLM + coding guide (Codex, GPT-6-based)</th>
<th style="text-align: right;">Rule-based</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">H1 Collision</td>
<td style="text-align: right;">7</td>
<td style="text-align: right;">0.67</td>
<td style="text-align: right;">0.4</td>
<td style="text-align: right;">0.31</td>
<td style="text-align: right;">0.26</td>
<td style="text-align: right;">0.62</td>
<td style="text-align: right;">0.92</td>
<td style="text-align: right;">0.92</td>
</tr>
<tr class="even">
<td style="text-align: left;">H2 Emergency obstruction</td>
<td style="text-align: right;">6</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0.33</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0.67</td>
<td style="text-align: right;">0.92</td>
<td style="text-align: right;">0.92</td>
</tr>
<tr class="odd">
<td style="text-align: left;">H3 Transit obstruction</td>
<td style="text-align: right;">8</td>
<td style="text-align: right;">0.46</td>
<td style="text-align: right;">0.22</td>
<td style="text-align: right;">0.22</td>
<td style="text-align: right;">0.21</td>
<td style="text-align: right;">0.47</td>
<td style="text-align: right;">0.86</td>
<td style="text-align: right;">1</td>
</tr>
<tr class="even">
<td style="text-align: left;">H4 Ped/accessibility</td>
<td style="text-align: right;">4</td>
<td style="text-align: right;">0.33</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0.4</td>
<td style="text-align: right;">0.43</td>
<td style="text-align: right;">1</td>
<td style="text-align: right;">1</td>
</tr>
<tr class="odd">
<td style="text-align: left;">H5 Occupant-related</td>
<td style="text-align: right;">9</td>
<td style="text-align: right;">0.46</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0.5</td>
<td style="text-align: right;">0.2</td>
<td style="text-align: right;">0.67</td>
<td style="text-align: right;">0.94</td>
<td style="text-align: right;">1</td>
</tr>
<tr class="even">
<td style="text-align: left;">H6 Multi-AV gridlock</td>
<td style="text-align: right;">17</td>
<td style="text-align: right;">0.94</td>
<td style="text-align: right;">0.94</td>
<td style="text-align: right;">0.67</td>
<td style="text-align: right;">0.48</td>
<td style="text-align: right;">0.71</td>
<td style="text-align: right;">1</td>
<td style="text-align: right;">1</td>
</tr>
<tr class="odd">
<td style="text-align: left;">H7 Single-AV obstruction</td>
<td style="text-align: right;">72</td>
<td style="text-align: right;">0.86</td>
<td style="text-align: right;">0.83</td>
<td style="text-align: right;">0.74</td>
<td style="text-align: right;">0.71</td>
<td style="text-align: right;">0.78</td>
<td style="text-align: right;">0.98</td>
<td style="text-align: right;">1</td>
</tr>
</tbody>
</table>
</div>
</figure>
</div>
<div id="tbl-pretrained-counts" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-tbl figure">
<figcaption class="quarto-float-caption-top quarto-float-caption quarto-float-tbl" id="tbl-pretrained-counts-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Table&nbsp;7: Number of incidents assigned to each hazard by the manual audit and by each pretrained model.
</figcaption>
<div aria-describedby="tbl-pretrained-counts-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<table class="caption-top table">
<colgroup>
<col style="width: 17%">
<col style="width: 10%">
<col style="width: 19%">
<col style="width: 22%">
<col style="width: 29%">
</colgroup>
<thead>
<tr class="header">
<th style="text-align: left;">Hazard</th>
<th style="text-align: right;">Manual audit</th>
<th style="text-align: right;">Zero-shot BART-large-MNLI</th>
<th style="text-align: right;">Zero-shot DeBERTa-v3-large NLI</th>
<th style="text-align: right;">Embedding similarity (mxbai-embed-large)</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">H1 Collision</td>
<td style="text-align: right;">7</td>
<td style="text-align: right;">38</td>
<td style="text-align: right;">39</td>
<td style="text-align: right;">6</td>
</tr>
<tr class="even">
<td style="text-align: left;">H2 Emergency obstruction</td>
<td style="text-align: right;">6</td>
<td style="text-align: right;">6</td>
<td style="text-align: right;">5</td>
<td style="text-align: right;">9</td>
</tr>
<tr class="odd">
<td style="text-align: left;">H3 Transit obstruction</td>
<td style="text-align: right;">8</td>
<td style="text-align: right;">1</td>
<td style="text-align: right;">11</td>
<td style="text-align: right;">22</td>
</tr>
<tr class="even">
<td style="text-align: left;">H4 Ped/accessibility</td>
<td style="text-align: right;">4</td>
<td style="text-align: right;">2</td>
<td style="text-align: right;">1</td>
<td style="text-align: right;">10</td>
</tr>
<tr class="odd">
<td style="text-align: left;">H5 Occupant-related</td>
<td style="text-align: right;">9</td>
<td style="text-align: right;">3</td>
<td style="text-align: right;">1</td>
<td style="text-align: right;">12</td>
</tr>
<tr class="even">
<td style="text-align: left;">H6 Multi-AV gridlock</td>
<td style="text-align: right;">17</td>
<td style="text-align: right;">10</td>
<td style="text-align: right;">8</td>
<td style="text-align: right;">11</td>
</tr>
<tr class="odd">
<td style="text-align: left;">H7 Single-AV obstruction</td>
<td style="text-align: right;">72</td>
<td style="text-align: right;">63</td>
<td style="text-align: right;">58</td>
<td style="text-align: right;">53</td>
</tr>
</tbody>
</table>
</div>
</figure>
</div>
<div id="tbl-classifier-tests" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-tbl figure">
<figcaption class="quarto-float-caption-top quarto-float-caption quarto-float-tbl" id="tbl-classifier-tests-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Table&nbsp;8: Paired comparisons of classifiers on the same incidents: exact McNemar test on correctness and paired-bootstrap 95% CI for the macro-F1 difference.
</figcaption>
<div aria-describedby="tbl-classifier-tests-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<table class="caption-top table">
<colgroup>
<col style="width: 24%">
<col style="width: 20%">
<col style="width: 10%">
<col style="width: 10%">
<col style="width: 7%">
<col style="width: 15%">
<col style="width: 10%">
</colgroup>
<thead>
<tr class="header">
<th style="text-align: left;">A</th>
<th style="text-align: left;">B</th>
<th style="text-align: right;">Only A correct</th>
<th style="text-align: right;">Only B correct</th>
<th style="text-align: left;">McNemar p</th>
<th style="text-align: left;">Macro-F1 A - B (95% CI)</th>
<th style="text-align: left;">CI excludes 0?</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">Zero-shot DeBERTa-v3-large NLI</td>
<td style="text-align: left;">Zero-shot BART-large-MNLI</td>
<td style="text-align: right;">7</td>
<td style="text-align: right;">17</td>
<td style="text-align: left;">0.064</td>
<td style="text-align: left;">-0.07 (-0.20 to +0.05)</td>
<td style="text-align: left;">No</td>
</tr>
<tr class="even">
<td style="text-align: left;">Embedding similarity (mxbai-embed-large)</td>
<td style="text-align: left;">Zero-shot BART-large-MNLI</td>
<td style="text-align: right;">28</td>
<td style="text-align: right;">15</td>
<td style="text-align: left;">0.066</td>
<td style="text-align: left;">+0.22 (+0.08 to +0.36)</td>
<td style="text-align: left;">Yes</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Zero-shot BART-large-MNLI</td>
<td style="text-align: left;">TF-IDF + logistic regression (CV)</td>
<td style="text-align: right;">10</td>
<td style="text-align: right;">35</td>
<td style="text-align: left;">&lt; 0.001</td>
<td style="text-align: left;">-0.14 (-0.29 to +0.02)</td>
<td style="text-align: left;">No</td>
</tr>
<tr class="even">
<td style="text-align: left;">Zero-shot DeBERTa-v3-large NLI</td>
<td style="text-align: left;">TF-IDF + logistic regression (CV)</td>
<td style="text-align: right;">7</td>
<td style="text-align: right;">42</td>
<td style="text-align: left;">&lt; 0.001</td>
<td style="text-align: left;">-0.21 (-0.39 to -0.03)</td>
<td style="text-align: left;">Yes</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Embedding similarity (mxbai-embed-large)</td>
<td style="text-align: left;">TF-IDF + logistic regression (CV)</td>
<td style="text-align: right;">19</td>
<td style="text-align: right;">31</td>
<td style="text-align: left;">0.119</td>
<td style="text-align: left;">+0.09 (-0.06 to +0.23)</td>
<td style="text-align: left;">No</td>
</tr>
</tbody>
</table>
</div>
</figure>
</div>
<div id="tbl-disagreements" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-tbl figure">
<figcaption class="quarto-float-caption-top quarto-float-caption quarto-float-tbl" id="tbl-disagreements-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Table&nbsp;9: Incidents where the rule classifier and the manual audit disagree.
</figcaption>
<div aria-describedby="tbl-disagreements-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<table class="caption-top table">
<colgroup>
<col style="width: 4%">
<col style="width: 2%">
<col style="width: 3%">
<col style="width: 51%">
<col style="width: 37%">
</colgroup>
<thead>
<tr class="header">
<th style="text-align: left;">Incident</th>
<th style="text-align: left;">Rule</th>
<th style="text-align: left;">Manual</th>
<th style="text-align: left;">Narrative</th>
<th style="text-align: left;">Note</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">INC-066</td>
<td style="text-align: left;">H2</td>
<td style="text-align: left;">H1</td>
<td style="text-align: left;">Traffic hazard due to a veh accident..need PD for traffic control..tow truck en route no eta..PD resp..Waymo able to move AV..no need for PD</td>
<td style="text-align: left;">Ambiguous: ‘veh accident’ with the Waymo subsequently moved and a tow en route suggests AV involvement.</td>
</tr>
</tbody>
</table>
</div>
</figure>
</div>
<div id="fig-classifiers" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-classifiers-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="assets/figures/fig-classifiers.png" class="img-fluid figure-img">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-classifiers-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;1: Macro-F1 of each classifier against the manual audit labels. Supervised models show mean ± 1 SD across cross-validation folds; pretrained models and the LLM use no training data (the LLM was given the written coding guide). The rule-based score is in-sample.
</figcaption>
</figure>
</div>
</section>
<section id="contributing-causes" class="level2" data-number="3.3">
<h2 data-number="3.3" class="anchored" data-anchor-id="contributing-causes"><span class="header-section-number">3.3</span> Contributing causes</h2>
<p><a href="#tbl-hazard-cause" class="quarto-xref">Table&nbsp;10</a> cross-tabulates hazard against contributing cause. Most narratives give no cause at all (“stalled”, “stuck”). That reflects the terse, truncated dispatcher text, and it is why cause is reported descriptively rather than used to define hazards.</p>
<div id="tbl-hazard-cause" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-tbl figure">
<figcaption class="quarto-float-caption-top quarto-float-caption quarto-float-tbl" id="tbl-hazard-cause-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Table&nbsp;10: Hazard (consequence) by contributing cause (mechanism), all 123 incidents.
</figcaption>
<div aria-describedby="tbl-hazard-cause-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<table class="caption-top table">
<colgroup>
<col style="width: 9%">
<col style="width: 6%">
<col style="width: 15%">
<col style="width: 12%">
<col style="width: 17%">
<col style="width: 7%">
<col style="width: 5%">
<col style="width: 11%">
<col style="width: 13%">
</colgroup>
<thead>
<tr class="header">
<th style="text-align: left;">Hazard</th>
<th style="text-align: right;">AV collision / contact</th>
<th style="text-align: right;">External event or scene (fire, crash, protest, police activity)</th>
<th style="text-align: right;">Infrastructure failure (signal or power outage)</th>
<th style="text-align: right;">Maneuver or routing edge case (turn, parking lot, cul-de-sac, queue)</th>
<th style="text-align: right;">Passenger condition or action</th>
<th style="text-align: right;">Tampering / vandalism</th>
<th style="text-align: right;">Unstated (stalled/stuck with no cause given)</th>
<th style="text-align: right;">Vehicle fault (hardware, battery, tire, sensor damage)</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">AV-involved collision</td>
<td style="text-align: right;">6</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0</td>
</tr>
<tr class="even">
<td style="text-align: left;">Emergency-response obstruction</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">5</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">2</td>
<td style="text-align: right;">0</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Transit / rail obstruction</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">1</td>
<td style="text-align: right;">1</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">6</td>
<td style="text-align: right;">0</td>
</tr>
<tr class="even">
<td style="text-align: left;">Pedestrian / accessibility obstruction</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">4</td>
<td style="text-align: right;">0</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Occupant-related immobilization</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">9</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0</td>
</tr>
<tr class="even">
<td style="text-align: left;">Multi-AV clustering / gridlock</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">1</td>
<td style="text-align: right;">2</td>
<td style="text-align: right;">6</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">8</td>
<td style="text-align: right;">0</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Single-AV traffic obstruction</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">2</td>
<td style="text-align: right;">3</td>
<td style="text-align: right;">6</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">1</td>
<td style="text-align: right;">47</td>
<td style="text-align: right;">13</td>
</tr>
</tbody>
</table>
</div>
</figure>
</div>
</section>
</section>
<section id="sec-impact" class="level1" data-number="4">
<h1 data-number="4"><span class="header-section-number">4</span> Impact scoring</h1>
<p>Each incident receives an impact level on the matrix’s 1–5 scale. The level is the <em>maximum</em> of three component scores: a hazard-specific consequence, a duration band, and an AV-cluster size. Taking the maximum means one serious attribute, such as a delayed ambulance, is never averaged away by benign ones. The rubric (<a href="#tbl-impact-rubric" class="quarto-xref">Table&nbsp;11</a>) is an explicit ordinal judgment, written down so that it can be challenged. Its anchors follow common practice: <em>Major</em> means interference with emergency services or a damaging collision, and <em>Severe</em> means a life-safety consequence.</p>
<div id="tbl-impact-rubric" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-tbl figure">
<figcaption class="quarto-float-caption-top quarto-float-caption quarto-float-tbl" id="tbl-impact-rubric-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Table&nbsp;11: Incident-level impact rubric (the highest criterion met sets the level).
</figcaption>
<div aria-describedby="tbl-impact-rubric-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<table class="caption-top table">
<colgroup>
<col style="width: 4%">
<col style="width: 7%">
<col style="width: 87%">
</colgroup>
<thead>
<tr class="header">
<th style="text-align: right;">Level</th>
<th style="text-align: left;">Impact</th>
<th style="text-align: left;">Criteria (any one suffices)</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: right;">1</td>
<td style="text-align: left;">Insignificant</td>
<td style="text-align: left;">General-traffic obstruction cleared in under 10 minutes.</td>
</tr>
<tr class="even">
<td style="text-align: right;">2</td>
<td style="text-align: left;">Minor</td>
<td style="text-align: left;">General-traffic obstruction of 10-60 minutes; 2-4 AVs clustered; non-medical occupant issue (asleep rider, door left open).</td>
</tr>
<tr class="odd">
<td style="text-align: right;">3</td>
<td style="text-align: left;">Significant</td>
<td style="text-align: left;">Obstruction lasting 60 minutes or more; public-transit or rail obstruction; crosswalk / curb-ramp / bike-lane obstruction; 5+ AVs gridlocked; occupant medical-welfare check.</td>
</tr>
<tr class="even">
<td style="text-align: right;">4</td>
<td style="text-align: left;">Major</td>
<td style="text-align: left;">Obstruction of emergency responders or an active emergency scene; AV-involved collision with no reported injury.</td>
</tr>
<tr class="odd">
<td style="text-align: right;">5</td>
<td style="text-align: left;">Severe</td>
<td style="text-align: left;">Emergency response obstructed during a life-threatening incident (unconscious patient, fire, persons trapped, shots fired), or an AV-involved collision with reported injury.</td>
</tr>
</tbody>
</table>
</div>
</figure>
</div>
<p><a href="#fig-hazard-impact" class="quarto-xref">Figure&nbsp;2</a> shows the resulting impact profile of each hazard. Duration drives the score for most H7 incidents. The hazard component drives it for H1–H5. Durations do not differ significantly across hazard classes (Kruskal–Wallis p = 0.302).</p>
<div id="fig-hazard-impact" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-hazard-impact-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="assets/figures/fig-hazard-impact.png" class="img-fluid figure-img">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-hazard-impact-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;2: Number of incidents by hazard and incident-level impact (all 123 incidents).
</figcaption>
</figure>
</div>
</section>
<section id="sec-frequency" class="level1" data-number="5">
<h1 data-number="5"><span class="header-section-number">5</span> Frequency estimation</h1>
<section id="model" class="level2" data-number="5.1">
<h2 data-number="5.1" class="anchored" data-anchor-id="model"><span class="header-section-number">5.1</span> Model</h2>
<p>Incidents of a given kind are modeled as a Poisson process with daily rate <span class="math inline">\(\lambda\)</span> over the <span class="math inline">\(T\)</span> = 184 covered days. With <span class="math inline">\(n\)</span> observed events, the maximum likelihood estimate is <span class="math inline">\(\hat\lambda = n/T\)</span>, and its exact 95% confidence interval follows from the chi-square quantiles <span class="citation" data-cites="garwood1936">(<a href="#ref-garwood1936" role="doc-biblioref">Garwood 1936</a>)</span>:</p>
<p><span class="math display">\[
\left[\tfrac{1}{2T}\chi^2_{0.025}(2n),\ \tfrac{1}{2T}\chi^2_{0.975}(2n+2)\right].
\]</span></p>
<p>For a Bayesian treatment that stays sensible at small <span class="math inline">\(n\)</span>, we use the Jeffreys prior <span class="math inline">\(p(\lambda) \propto \lambda^{-1/2}\)</span> <span class="citation" data-cites="jeffreys1946">(<a href="#ref-jeffreys1946" role="doc-biblioref">Jeffreys 1946</a>)</span>, giving the posterior</p>
<p><span class="math display">\[
\lambda \mid n \sim \operatorname{Gamma}\!\left(n + \tfrac12,\ T\right),
\]</span></p>
<p>and the posterior-predictive probability of at least one event in the next <span class="math inline">\(h\)</span> days (a negative-binomial predictive):</p>
<p><span class="math display">\[
P(N_h \ge 1 \mid n) = 1 - \left(\frac{T}{T + h}\right)^{n + 1/2}.
\]</span></p>
<p><strong>Why Bayesian for the risk matrix.</strong> We report both frameworks. The classical estimate and exact interval describe each rate, and the Bayesian predictive probability sets the matrix’s probability axis, for four reasons:</p>
<ol type="1">
<li><strong>It answers the matrix’s question.</strong> The probability axis asks how likely at least one qualifying incident is in the next 30 days, a statement about <em>future events</em>. The posterior predictive answers that directly. The usual frequentist shortcut, <span class="math inline">\(1 - e^{-h\hat\lambda}\)</span>, plugs in <span class="math inline">\(\hat\lambda = n/T\)</span> as if the rate were known exactly.</li>
<li><strong>It carries rate uncertainty into the probability.</strong> The consequential hazards rest on 3–6 incidents, and their rates are uncertain by a factor of about five (<a href="#fig-hazard-rates" class="quarto-xref">Figure&nbsp;3</a>). The predictive probability averages over that uncertainty instead of ignoring it.</li>
<li><strong>It behaves sensibly with few or zero events.</strong> A plug-in estimate gives a hazard never yet observed a probability of exactly zero. The Jeffreys predictive gives a small non-zero probability, and it tempers over-confidence when <span class="math inline">\(n\)</span> is 3 or 4.</li>
<li><strong>It supports direct probability statements.</strong> “A 41% chance of at least one life-threatening emergency obstruction in the next 30 days” is a valid Bayesian statement. A confidence interval does not license that reading.</li>
</ol>
<p>The Jeffreys prior is a standard reference prior: it encodes no opinion about AVs, so the data drive the result. The framework also extends naturally. Fleet mileage can enter as exposure, and evidence from other cities as an informative prior. The reference risk-matrix template offered a Bayesian basis as one of its options. In this data the choice is principled rather than decisive: the plug-in probability places every hazard in the same cell (<a href="#tbl-sensitivity" class="quarto-xref">Table&nbsp;16</a>, “Plug-in MLE”).</p>
<p>The log has no exposure denominator, such as AV trips or vehicle-miles. Rates are therefore <strong>per calendar day</strong>. They describe the system as operated in San Francisco in 2025, not per-mile safety.</p>
</section>
<section id="results" class="level2" data-number="5.2">
<h2 data-number="5.2" class="anchored" data-anchor-id="results"><span class="header-section-number">5.2</span> Results</h2>
<p>Blocking incidents occur at 19.6 per 30 days (95% CI 16.2–23.4), about 4.6 per week, or one every 1.5 days. Single-AV traffic obstruction (H7) accounts for most of them, at about 11.41 per 30 days. Even the rarest hazards recur on a monthly timescale: collisions (H1) and emergency-response obstruction (H2) each average one every 31 days (<a href="#tbl-frequency" class="quarto-xref">Table&nbsp;12</a>, <a href="#fig-hazard-rates" class="quarto-xref">Figure&nbsp;3</a>).</p>
<div id="tbl-frequency" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-tbl figure">
<figcaption class="quarto-float-caption-top quarto-float-caption quarto-float-tbl" id="tbl-frequency-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Table&nbsp;12: Hazard frequencies over the 184 covered days (Mar, Jun-Oct 2025).
</figcaption>
<div aria-describedby="tbl-frequency-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<table class="caption-top table">
<colgroup>
<col style="width: 4%">
<col style="width: 22%">
<col style="width: 2%">
<col style="width: 5%">
<col style="width: 13%">
<col style="width: 17%">
<col style="width: 11%">
<col style="width: 10%">
<col style="width: 12%">
</colgroup>
<thead>
<tr class="header">
<th style="text-align: left;">Code</th>
<th style="text-align: left;">Hazard</th>
<th style="text-align: right;">n</th>
<th style="text-align: left;">Share</th>
<th style="text-align: left;">MLE per 30 d (95% CI)</th>
<th style="text-align: left;">Posterior per 30 d (95% CrI)</th>
<th style="text-align: right;">Mean days between</th>
<th style="text-align: right;">P(&gt;=1 in 30 d)</th>
<th style="text-align: left;">Band (all impacts)</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">H1</td>
<td style="text-align: left;">AV-involved collision</td>
<td style="text-align: right;">6</td>
<td style="text-align: left;">5%</td>
<td style="text-align: left;">0.98 (0.36-2.13)</td>
<td style="text-align: left;">1.06 (0.41-2.02)</td>
<td style="text-align: right;">30.7</td>
<td style="text-align: right;">0.625</td>
<td style="text-align: left;">Likely</td>
</tr>
<tr class="even">
<td style="text-align: left;">H2</td>
<td style="text-align: left;">Emergency-response obstruction</td>
<td style="text-align: right;">6</td>
<td style="text-align: left;">5%</td>
<td style="text-align: left;">0.98 (0.36-2.13)</td>
<td style="text-align: left;">1.06 (0.41-2.02)</td>
<td style="text-align: right;">30.7</td>
<td style="text-align: right;">0.625</td>
<td style="text-align: left;">Likely</td>
</tr>
<tr class="odd">
<td style="text-align: left;">H3</td>
<td style="text-align: left;">Transit / rail obstruction</td>
<td style="text-align: right;">8</td>
<td style="text-align: left;">7%</td>
<td style="text-align: left;">1.30 (0.56-2.57)</td>
<td style="text-align: left;">1.39 (0.62-2.46)</td>
<td style="text-align: right;">23</td>
<td style="text-align: right;">0.723</td>
<td style="text-align: left;">Likely</td>
</tr>
<tr class="even">
<td style="text-align: left;">H4</td>
<td style="text-align: left;">Pedestrian / accessibility obstruction</td>
<td style="text-align: right;">4</td>
<td style="text-align: left;">3%</td>
<td style="text-align: left;">0.65 (0.18-1.67)</td>
<td style="text-align: left;">0.73 (0.22-1.55)</td>
<td style="text-align: right;">46</td>
<td style="text-align: right;">0.493</td>
<td style="text-align: left;">Moderate</td>
</tr>
<tr class="odd">
<td style="text-align: left;">H5</td>
<td style="text-align: left;">Occupant-related immobilization</td>
<td style="text-align: right;">9</td>
<td style="text-align: left;">8%</td>
<td style="text-align: left;">1.47 (0.67-2.79)</td>
<td style="text-align: left;">1.55 (0.73-2.68)</td>
<td style="text-align: right;">20.4</td>
<td style="text-align: right;">0.762</td>
<td style="text-align: left;">Likely</td>
</tr>
<tr class="even">
<td style="text-align: left;">H6</td>
<td style="text-align: left;">Multi-AV clustering / gridlock</td>
<td style="text-align: right;">17</td>
<td style="text-align: left;">14%</td>
<td style="text-align: left;">2.77 (1.61-4.44)</td>
<td style="text-align: left;">2.85 (1.68-4.34)</td>
<td style="text-align: right;">10.8</td>
<td style="text-align: right;">0.929</td>
<td style="text-align: left;">Almost certain</td>
</tr>
<tr class="odd">
<td style="text-align: left;">H7</td>
<td style="text-align: left;">Single-AV traffic obstruction</td>
<td style="text-align: right;">70</td>
<td style="text-align: left;">58%</td>
<td style="text-align: left;">11.41 (8.90-14.42)</td>
<td style="text-align: left;">11.49 (8.97-14.33)</td>
<td style="text-align: right;">2.6</td>
<td style="text-align: right;">1</td>
<td style="text-align: left;">Almost certain</td>
</tr>
<tr class="even">
<td style="text-align: left;">All</td>
<td style="text-align: left;">All blocking incidents</td>
<td style="text-align: right;">120</td>
<td style="text-align: left;">100%</td>
<td style="text-align: left;">19.57 (16.22-23.40)</td>
<td style="text-align: left;">19.65 (16.30-23.31)</td>
<td style="text-align: right;">1.5</td>
<td style="text-align: right;">1</td>
<td style="text-align: left;">Almost certain</td>
</tr>
</tbody>
</table>
</div>
</figure>
</div>
<div id="fig-hazard-rates" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-hazard-rates-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="assets/figures/fig-hazard-rates.png" class="img-fluid figure-img">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-hazard-rates-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;3: Posterior mean frequency per 30 days with 95% Jeffreys credible intervals (log scale).
</figcaption>
</figure>
</div>
</section>
</section>
<section id="sec-trends" class="level1" data-number="6">
<h1 data-number="6"><span class="header-section-number">6</span> Is anything changing over time?</h1>
<section id="choosing-the-tests" class="level2" data-number="6.1">
<h2 data-number="6.1" class="anchored" data-anchor-id="choosing-the-tests"><span class="header-section-number">6.1</span> Choosing the tests</h2>
<p>Two features of the data rule out normal-theory methods. There are only six monthly counts, and durations are strongly right-skewed: skewness ≈ 3.9, excess kurtosis ≈ 22, Shapiro–Wilk <span class="math inline">\(p &lt; 10^{-15}\)</span> <span class="citation" data-cites="shapiro1965">(<a href="#ref-shapiro1965" role="doc-biblioref">Shapiro and Wilk 1965</a>)</span>. Log-durations, by contrast, are approximately normal (Shapiro–Wilk p ≈ 0.38). Each question is therefore matched to a test whose assumptions hold:</p>
<ul>
<li><strong>Monotone trend in monthly rates: Mann–Kendall</strong> <span class="citation" data-cites="mann1945 kendall1975">(<a href="#ref-mann1945" role="doc-biblioref">Mann 1945</a>; <a href="#ref-kendall1975" role="doc-biblioref">Kendall 1975</a>)</span>. The statistic is <span class="math display">\[S = \sum_{i&lt;j} \operatorname{sgn}(x_j - x_i).\]</span> With <span class="math inline">\(n = 6\)</span>, its null distribution is computed <em>exactly</em> by enumerating all <span class="math inline">\(6! = 720\)</span> orderings, so no normal approximation is needed. Sen’s slope <span class="citation" data-cites="sen1968">(<a href="#ref-sen1968" role="doc-biblioref">Sen 1968</a>)</span> gives the magnitude.</li>
<li><strong>Equal rates across months:</strong> the Poisson homogeneity chi-square, <span class="math inline">\(\sum_m (n_m - E_m)^2/E_m\)</span> with <span class="math inline">\(E_m \propto\)</span> days in month <span class="math inline">\(m\)</span>.</li>
<li><strong>Two-period rate comparison:</strong> the exact conditional binomial test. Given <span class="math inline">\(n_1 + n_2\)</span>, under <span class="math inline">\(H_0\)</span> the count <span class="math inline">\(n_2\)</span> is <span class="math inline">\(\operatorname{Bin}\!\left(n_1 + n_2,\ \tfrac{T_2}{T_1 + T_2}\right)\)</span>.</li>
<li><strong>Parametric cross-check:</strong> a Poisson GLM with a <span class="math inline">\(\log(\text{days})\)</span> offset, giving an interpretable rate ratio per month.</li>
<li><strong>Duration differences across months: Kruskal–Wallis</strong> <span class="citation" data-cites="kruskal1952">(<a href="#ref-kruskal1952" role="doc-biblioref">Kruskal and Wallis 1952</a>)</span>, <span class="math display">\[H = \frac{12}{N(N+1)} \sum_g \frac{R_g^2}{n_g} - 3(N+1).\]</span></li>
<li><strong>Two months: Mann–Whitney</strong> <span class="citation" data-cites="mann1947">(<a href="#ref-mann1947" role="doc-biblioref">Mann and Whitney 1947</a>)</span>, <span class="math display">\[U = \sum_{i}\sum_{j}\left[\mathbb 1(x_i &gt; y_j) + \tfrac12 \mathbb 1(x_i = y_j)\right].\]</span></li>
<li><strong>An <em>ordered</em> shift across months: Jonckheere–Terpstra</strong> <span class="citation" data-cites="jonckheere1954">(<a href="#ref-jonckheere1954" role="doc-biblioref">Jonckheere 1954</a>)</span>, <span class="math inline">\(J = \sum_{g&lt;h} U_{gh}\)</span>, with a permutation p-value. This is more powerful than Kruskal–Wallis against monotone alternatives.</li>
<li><strong>Trend in a proportion</strong> (the multi-AV share): <strong>Cochran–Armitage</strong> <span class="citation" data-cites="armitage1955">(<a href="#ref-armitage1955" role="doc-biblioref">Armitage 1955</a>)</span>.</li>
<li><strong>Hazard mix by period:</strong> a chi-square statistic with a Monte-Carlo permutation p-value, because 71% of expected cell counts are below 5.</li>
</ul>
</section>
<section id="incident-counts-and-durations" class="level2" data-number="6.2">
<h2 data-number="6.2" class="anchored" data-anchor-id="incident-counts-and-durations"><span class="header-section-number">6.2</span> Incident counts and durations</h2>
<p>The monthly rate fluctuates between about 11 and 24 per 30 days (<a href="#fig-monthly-rate" class="quarto-xref">Figure&nbsp;4</a>). Every fluctuation is consistent with a constant underlying rate:</p>
<ul>
<li>Poisson homogeneity: p = 0.2.</li>
<li>Mann–Kendall: <span class="math inline">\(\tau\)</span> = 0.13, exact p = 0.86.</li>
<li>March versus October rate ratio: 1.04 (95% CI 0.57–1.9), p = 1.</li>
<li>Poisson GLM rate ratio: 0.983 per month (0.91–1.063), p = 0.67.</li>
</ul>
<p>Durations also show no significant change (<a href="#fig-duration-month" class="quarto-xref">Figure&nbsp;5</a>):</p>
<ul>
<li>Kruskal–Wallis: H = 6.88, p = 0.23.</li>
<li>Jonckheere–Terpstra: p = 0.19.</li>
<li>Spearman: <span class="math inline">\(\rho\)</span> = 0.1, p = 0.29.</li>
<li>The Theil–Sen slope of log-duration is 5.3% per 30 days, with a 95% interval of -5.1% to +16.8% that comfortably includes zero.</li>
</ul>
<p><strong>Replicating the class result.</strong> The class worksheet’s March-vs-October Mann–Whitney test reproduces exactly (W = 377.5, p = 0.064) once the 603-minute March 12 record is dropped, as the worksheet did. With that record included, p = 0.123. Either way, the October median is longer than March’s, but the difference is not significant at the 5% level.</p>
<p>Absence of evidence is not evidence of absence. With six months of data, these tests can detect only large trends. The defensible statement is that the data show <strong>no detectable change</strong>, not that nothing is changing.</p>
<div id="fig-monthly-rate" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-monthly-rate-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="assets/figures/fig-monthly-rate.png" class="img-fluid figure-img">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-monthly-rate-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;4: Monthly incident rate per 30 days with exact 95% Poisson intervals. Gray bands mark months absent from (or only partially present in) the log.
</figcaption>
</figure>
</div>
<div id="fig-duration-month" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-duration-month-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="assets/figures/fig-duration-month.png" class="img-fluid figure-img">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-duration-month-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;5: Incident duration by month (log scale). Box plots show medians and quartiles; points are individual incidents.
</figcaption>
</figure>
</div>
</section>
<section id="sec-mix" class="level2" data-number="6.3">
<h2 data-number="6.3" class="anchored" data-anchor-id="sec-mix"><span class="header-section-number">6.3</span> The hazard mix shift is a reporting artifact</h2>
<p>One test does reject. The hazard mix differs between March–July and August–October (permutation p = 0.007; <a href="#fig-hazard-period" class="quarto-xref">Figure&nbsp;6</a>). Taken at face value, this would suggest emergency and transit obstructions are new. But the composition of the <em>narratives</em> changed at the same moment. 98% of March–July narratives are truncated fragments, against 41% in August–October (Fisher p &lt; 0.001). Context such as “fire”, “medic”, or “Muni” is exactly what a 50-character fragment loses. Two further checks support this reading:</p>
<ul>
<li>The shift is a reshuffle among the text-dependent classes H1–H5. Their <em>combined</em> share does not differ between periods (Fisher p = 0.22).</li>
<li>The one composition measure taken from a structured field, the multi-AV share, shows no trend (Cochran–Armitage p = 0.17).</li>
</ul>
<p>The defensible conclusion is that the shift is <strong>not attributable to a change in AV behavior</strong>. It is most plausibly a recording artifact.</p>
<div id="tbl-tests" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-tbl figure">
<figcaption class="quarto-float-caption-top quarto-float-caption quarto-float-tbl" id="tbl-tests-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Table&nbsp;13: Statistical tests for change over time (covered months).
</figcaption>
<div aria-describedby="tbl-tests-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<table class="caption-top table">
<colgroup>
<col style="width: 18%">
<col style="width: 29%">
<col style="width: 18%">
<col style="width: 19%">
<col style="width: 4%">
<col style="width: 9%">
</colgroup>
<thead>
<tr class="header">
<th style="text-align: left;">Quantity</th>
<th style="text-align: left;">Null hypothesis</th>
<th style="text-align: left;">Test</th>
<th style="text-align: left;">Statistic / effect</th>
<th style="text-align: left;">p</th>
<th style="text-align: left;">Reject at 0.05?</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">Monthly incident rate</td>
<td style="text-align: left;">Equal rate across months</td>
<td style="text-align: left;">Poisson homogeneity chi-square</td>
<td style="text-align: left;">chi2(5) = 7.30</td>
<td style="text-align: left;">0.199</td>
<td style="text-align: left;">No</td>
</tr>
<tr class="even">
<td style="text-align: left;">Monthly incident rate</td>
<td style="text-align: left;">No monotone trend</td>
<td style="text-align: left;">Mann-Kendall (exact)</td>
<td style="text-align: left;">S = 2, tau = 0.13</td>
<td style="text-align: left;">0.856</td>
<td style="text-align: left;">No</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Monthly incident rate</td>
<td style="text-align: left;">Mar rate = Oct rate</td>
<td style="text-align: left;">Exact conditional binomial</td>
<td style="text-align: left;">RR = 1.04 (0.57-1.90)</td>
<td style="text-align: left;">1.000</td>
<td style="text-align: left;">No</td>
</tr>
<tr class="even">
<td style="text-align: left;">Monthly incident rate</td>
<td style="text-align: left;">No log-linear trend</td>
<td style="text-align: left;">Poisson GLM, log(days) offset</td>
<td style="text-align: left;">RR/month = 0.983 (0.910-1.063)</td>
<td style="text-align: left;">0.671</td>
<td style="text-align: left;">No</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Duration</td>
<td style="text-align: left;">Same distribution in all months</td>
<td style="text-align: left;">Kruskal-Wallis</td>
<td style="text-align: left;">H(5) = 6.88, eps2 = 0.017</td>
<td style="text-align: left;">0.229</td>
<td style="text-align: left;">No</td>
</tr>
<tr class="even">
<td style="text-align: left;">Duration</td>
<td style="text-align: left;">Mar = Oct</td>
<td style="text-align: left;">Mann-Whitney U</td>
<td style="text-align: left;">U = 222.5, r_rb = 0.26</td>
<td style="text-align: left;">0.123</td>
<td style="text-align: left;">No</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Duration</td>
<td style="text-align: left;">Mar = Oct (603-min record dropped, replicates class sheet)</td>
<td style="text-align: left;">Mann-Whitney U</td>
<td style="text-align: left;">W = 377.5</td>
<td style="text-align: left;">0.064</td>
<td style="text-align: left;">No</td>
</tr>
<tr class="even">
<td style="text-align: left;">Duration</td>
<td style="text-align: left;">No ordered shift across months</td>
<td style="text-align: left;">Jonckheere-Terpstra (permutation)</td>
<td style="text-align: left;">JT = 3248, z = 1.32</td>
<td style="text-align: left;">0.186</td>
<td style="text-align: left;">No</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Duration</td>
<td style="text-align: left;">No association with date</td>
<td style="text-align: left;">Spearman; Theil-Sen on log duration</td>
<td style="text-align: left;">rho = 0.10; +5.3%/30 d (-5.1 to +16.8)</td>
<td style="text-align: left;">0.291</td>
<td style="text-align: left;">No</td>
</tr>
<tr class="even">
<td style="text-align: left;">Hazard mix</td>
<td style="text-align: left;">Independent of period</td>
<td style="text-align: left;">Permutation chi-square</td>
<td style="text-align: left;">chi2 = 16.43</td>
<td style="text-align: left;">0.007</td>
<td style="text-align: left;">Yes</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Narrative truncation</td>
<td style="text-align: left;">Independent of period</td>
<td style="text-align: left;">Fisher exact</td>
<td style="text-align: left;">98% vs 41% truncated</td>
<td style="text-align: left;">&lt; 0.001</td>
<td style="text-align: left;">Yes</td>
</tr>
<tr class="even">
<td style="text-align: left;">Text-dependent hazards (H1-H5) share</td>
<td style="text-align: left;">Independent of period</td>
<td style="text-align: left;">Fisher exact</td>
<td style="text-align: left;">22% vs 33%</td>
<td style="text-align: left;">0.223</td>
<td style="text-align: left;">No</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Multi-AV share</td>
<td style="text-align: left;">No monotone trend</td>
<td style="text-align: left;">Cochran-Armitage</td>
<td style="text-align: left;">z = 1.37</td>
<td style="text-align: left;">0.169</td>
<td style="text-align: left;">No</td>
</tr>
</tbody>
</table>
</div>
</figure>
</div>
<div id="fig-hazard-period" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-hazard-period-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="assets/figures/fig-hazard-period.png" class="img-fluid figure-img">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-hazard-period-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;6: Share of each period’s incidents by hazard class.
</figcaption>
</figure>
</div>
</section>
</section>
<section id="sec-risk" class="level1" data-number="7">
<h1 data-number="7"><span class="header-section-number">7</span> Risk matrix</h1>
<section id="probability-and-impact-bands" class="level2" data-number="7.1">
<h2 data-number="7.1" class="anchored" data-anchor-id="probability-and-impact-bands"><span class="header-section-number">7.1</span> Probability and impact bands</h2>
<p>The matrix structure, labels, cell levels, and colors follow the team’s reference template. Its risk level is a <em>lookup</em> per cell, not a threshold on the probability × impact score: score 4 is <em>Low</em> at (2, 2) but <em>Medium</em> at (1, 4).</p>
<ul>
<li><strong>Probability</strong> is the posterior-predictive <span class="math inline">\(p = P(N_{30} \ge 1)\)</span>. A 30-day horizon matches a monthly operations-review cycle. The bands are Rare <span class="math inline">\(&lt; 0.05 \le\)</span> Unlikely <span class="math inline">\(&lt; 0.25 \le\)</span> Moderate <span class="math inline">\(&lt; 0.50 \le\)</span> Likely <span class="math inline">\(&lt; 0.90 \le\)</span> Almost certain.</li>
<li><strong>Impact</strong> is the incident-level score from <a href="#sec-impact" class="quarto-xref">Section&nbsp;4</a>.</li>
</ul>
</section>
<section id="risk-curve-placement" class="level2" data-number="7.2">
<h2 data-number="7.2" class="anchored" data-anchor-id="risk-curve-placement"><span class="header-section-number">7.2</span> Risk-curve placement</h2>
<p>A hazard does not have a single consequence. Collisions range from minor to injurious, and emergency obstructions from routine to life-threatening. The common shortcut pairs a hazard’s <em>total</em> frequency with its <em>worst</em> (or 90th-percentile) consequence. That overstates risk, because the worst outcome is rarer than the hazard as a whole. We instead evaluate the hazard’s <strong>risk curve</strong>. For hazard <span class="math inline">\(h\)</span> and impact tier <span class="math inline">\(k\)</span>, let</p>
<p><span class="math display">\[
n_{h,\ge k} = \#\{\text{incidents of } h \text{ with impact} \ge k\},\qquad
p_{h,k} = 1 - \left(\frac{T}{T+30}\right)^{n_{h,\ge k} + 1/2}.
\]</span></p>
<p>Each tier <span class="math inline">\(k\)</span> that was observed gives a candidate cell <span class="math inline">\(\big(\mathrm{band}(p_{h,k}),\, k\big)\)</span>. The hazard is placed at</p>
<p><span class="math display">\[
k^*_h = \arg\max_{k \le k^{\max}_h} \; \mathrm{Level}\!\big(\mathrm{band}(p_{h,k}),\, k\big),
\]</span></p>
<p>with ties broken toward the higher impact. Probability and impact then always describe <strong>the same event</strong>, “an <span class="math inline">\(h\)</span> incident at least as severe as <span class="math inline">\(k\)</span>”. Tiers that never occurred are not extrapolated (<a href="#tbl-risk-curves" class="quarto-xref">Table&nbsp;14</a>).</p>
<div id="tbl-risk-curves" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-tbl figure">
<figcaption class="quarto-float-caption-top quarto-float-caption quarto-float-tbl" id="tbl-risk-curves-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Table&nbsp;14: Risk-curve candidates: each observed impact tier with its own frequency and risk level.
</figcaption>
<div aria-describedby="tbl-risk-curves-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<table class="caption-top table">
<colgroup>
<col style="width: 10%">
<col style="width: 17%">
<col style="width: 22%">
<col style="width: 18%">
<col style="width: 16%">
<col style="width: 14%">
</colgroup>
<thead>
<tr class="header">
<th style="text-align: left;">Hazard</th>
<th style="text-align: left;">Impact tier k</th>
<th style="text-align: right;">n with impact &gt;= k</th>
<th style="text-align: right;">P(&gt;=1 in 30 d)</th>
<th style="text-align: left;">Probability</th>
<th style="text-align: left;">Risk level</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">H1</td>
<td style="text-align: left;">1 Insignificant</td>
<td style="text-align: right;">6</td>
<td style="text-align: right;">0.625</td>
<td style="text-align: left;">Likely</td>
<td style="text-align: left;">Medium</td>
</tr>
<tr class="even">
<td style="text-align: left;">H1</td>
<td style="text-align: left;">2 Minor</td>
<td style="text-align: right;">6</td>
<td style="text-align: right;">0.625</td>
<td style="text-align: left;">Likely</td>
<td style="text-align: left;">Medium</td>
</tr>
<tr class="odd">
<td style="text-align: left;">H1</td>
<td style="text-align: left;">3 Significant</td>
<td style="text-align: right;">6</td>
<td style="text-align: right;">0.625</td>
<td style="text-align: left;">Likely</td>
<td style="text-align: left;">High</td>
</tr>
<tr class="even">
<td style="text-align: left;">H1</td>
<td style="text-align: left;">4 Major</td>
<td style="text-align: right;">6</td>
<td style="text-align: right;">0.625</td>
<td style="text-align: left;">Likely</td>
<td style="text-align: left;">Very high</td>
</tr>
<tr class="odd">
<td style="text-align: left;">H2</td>
<td style="text-align: left;">1 Insignificant</td>
<td style="text-align: right;">6</td>
<td style="text-align: right;">0.625</td>
<td style="text-align: left;">Likely</td>
<td style="text-align: left;">Medium</td>
</tr>
<tr class="even">
<td style="text-align: left;">H2</td>
<td style="text-align: left;">2 Minor</td>
<td style="text-align: right;">6</td>
<td style="text-align: right;">0.625</td>
<td style="text-align: left;">Likely</td>
<td style="text-align: left;">Medium</td>
</tr>
<tr class="odd">
<td style="text-align: left;">H2</td>
<td style="text-align: left;">3 Significant</td>
<td style="text-align: right;">6</td>
<td style="text-align: right;">0.625</td>
<td style="text-align: left;">Likely</td>
<td style="text-align: left;">High</td>
</tr>
<tr class="even">
<td style="text-align: left;">H2</td>
<td style="text-align: left;">4 Major</td>
<td style="text-align: right;">6</td>
<td style="text-align: right;">0.625</td>
<td style="text-align: left;">Likely</td>
<td style="text-align: left;">Very high</td>
</tr>
<tr class="odd">
<td style="text-align: left;">H2</td>
<td style="text-align: left;">5 Severe</td>
<td style="text-align: right;">3</td>
<td style="text-align: right;">0.411</td>
<td style="text-align: left;">Moderate</td>
<td style="text-align: left;">Very high</td>
</tr>
<tr class="even">
<td style="text-align: left;">H3</td>
<td style="text-align: left;">1 Insignificant</td>
<td style="text-align: right;">8</td>
<td style="text-align: right;">0.723</td>
<td style="text-align: left;">Likely</td>
<td style="text-align: left;">Medium</td>
</tr>
<tr class="odd">
<td style="text-align: left;">H3</td>
<td style="text-align: left;">2 Minor</td>
<td style="text-align: right;">8</td>
<td style="text-align: right;">0.723</td>
<td style="text-align: left;">Likely</td>
<td style="text-align: left;">Medium</td>
</tr>
<tr class="even">
<td style="text-align: left;">H3</td>
<td style="text-align: left;">3 Significant</td>
<td style="text-align: right;">8</td>
<td style="text-align: right;">0.723</td>
<td style="text-align: left;">Likely</td>
<td style="text-align: left;">High</td>
</tr>
<tr class="odd">
<td style="text-align: left;">H4</td>
<td style="text-align: left;">1 Insignificant</td>
<td style="text-align: right;">4</td>
<td style="text-align: right;">0.493</td>
<td style="text-align: left;">Moderate</td>
<td style="text-align: left;">Low</td>
</tr>
<tr class="even">
<td style="text-align: left;">H4</td>
<td style="text-align: left;">2 Minor</td>
<td style="text-align: right;">4</td>
<td style="text-align: right;">0.493</td>
<td style="text-align: left;">Moderate</td>
<td style="text-align: left;">Medium</td>
</tr>
<tr class="odd">
<td style="text-align: left;">H4</td>
<td style="text-align: left;">3 Significant</td>
<td style="text-align: right;">4</td>
<td style="text-align: right;">0.493</td>
<td style="text-align: left;">Moderate</td>
<td style="text-align: left;">Medium</td>
</tr>
<tr class="even">
<td style="text-align: left;">H5</td>
<td style="text-align: left;">1 Insignificant</td>
<td style="text-align: right;">9</td>
<td style="text-align: right;">0.762</td>
<td style="text-align: left;">Likely</td>
<td style="text-align: left;">Medium</td>
</tr>
<tr class="odd">
<td style="text-align: left;">H5</td>
<td style="text-align: left;">2 Minor</td>
<td style="text-align: right;">9</td>
<td style="text-align: right;">0.762</td>
<td style="text-align: left;">Likely</td>
<td style="text-align: left;">Medium</td>
</tr>
<tr class="even">
<td style="text-align: left;">H5</td>
<td style="text-align: left;">3 Significant</td>
<td style="text-align: right;">3</td>
<td style="text-align: right;">0.411</td>
<td style="text-align: left;">Moderate</td>
<td style="text-align: left;">Medium</td>
</tr>
<tr class="odd">
<td style="text-align: left;">H6</td>
<td style="text-align: left;">1 Insignificant</td>
<td style="text-align: right;">17</td>
<td style="text-align: right;">0.929</td>
<td style="text-align: left;">Almost certain</td>
<td style="text-align: left;">Medium</td>
</tr>
<tr class="even">
<td style="text-align: left;">H6</td>
<td style="text-align: left;">2 Minor</td>
<td style="text-align: right;">17</td>
<td style="text-align: right;">0.929</td>
<td style="text-align: left;">Almost certain</td>
<td style="text-align: left;">High</td>
</tr>
<tr class="odd">
<td style="text-align: left;">H6</td>
<td style="text-align: left;">3 Significant</td>
<td style="text-align: right;">10</td>
<td style="text-align: right;">0.795</td>
<td style="text-align: left;">Likely</td>
<td style="text-align: left;">High</td>
</tr>
<tr class="even">
<td style="text-align: left;">H7</td>
<td style="text-align: left;">1 Insignificant</td>
<td style="text-align: right;">70</td>
<td style="text-align: right;">1</td>
<td style="text-align: left;">Almost certain</td>
<td style="text-align: left;">Medium</td>
</tr>
<tr class="odd">
<td style="text-align: left;">H7</td>
<td style="text-align: left;">2 Minor</td>
<td style="text-align: right;">48</td>
<td style="text-align: right;">0.999</td>
<td style="text-align: left;">Almost certain</td>
<td style="text-align: left;">High</td>
</tr>
<tr class="even">
<td style="text-align: left;">H7</td>
<td style="text-align: left;">3 Significant</td>
<td style="text-align: right;">17</td>
<td style="text-align: right;">0.929</td>
<td style="text-align: left;">Almost certain</td>
<td style="text-align: left;">Very high</td>
</tr>
</tbody>
</table>
</div>
</figure>
</div>
<div id="fig-risk-matrix" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-risk-matrix-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="assets/figures/fig-risk-matrix.png" class="img-fluid figure-img">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-risk-matrix-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;7: 5×5 risk matrix of AV blocking hazards. Probability is the Jeffreys posterior-predictive probability of at least one qualifying incident in the next 30 days. Impact is the governing tier of each hazard’s risk curve.
</figcaption>
</figure>
</div>
<div id="tbl-risk-placement" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-tbl figure">
<figcaption class="quarto-float-caption-top quarto-float-caption quarto-float-tbl" id="tbl-risk-placement-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Table&nbsp;15: Risk-matrix placement of each hazard (Bayesian predictive probability, 30-day horizon).
</figcaption>
<div aria-describedby="tbl-risk-placement-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<table class="caption-top table">
<colgroup>
<col style="width: 5%">
<col style="width: 26%">
<col style="width: 3%">
<col style="width: 16%">
<col style="width: 11%">
<col style="width: 11%">
<col style="width: 9%">
<col style="width: 14%">
</colgroup>
<thead>
<tr class="header">
<th style="text-align: left;">Code</th>
<th style="text-align: left;">Hazard</th>
<th style="text-align: right;">n</th>
<th style="text-align: right;">n at governing impact</th>
<th style="text-align: right;">P(&gt;=1 in 30 d)</th>
<th style="text-align: left;">Probability</th>
<th style="text-align: left;">Impact</th>
<th style="text-align: left;">Risk level (score)</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">H1</td>
<td style="text-align: left;">AV-involved collision</td>
<td style="text-align: right;">6</td>
<td style="text-align: right;">6</td>
<td style="text-align: right;">0.63</td>
<td style="text-align: left;">4 Likely</td>
<td style="text-align: left;">4 Major</td>
<td style="text-align: left;">Very high (16)</td>
</tr>
<tr class="even">
<td style="text-align: left;">H2</td>
<td style="text-align: left;">Emergency-response obstruction</td>
<td style="text-align: right;">6</td>
<td style="text-align: right;">3</td>
<td style="text-align: right;">0.41</td>
<td style="text-align: left;">3 Moderate</td>
<td style="text-align: left;">5 Severe</td>
<td style="text-align: left;">Very high (15)</td>
</tr>
<tr class="odd">
<td style="text-align: left;">H3</td>
<td style="text-align: left;">Transit / rail obstruction</td>
<td style="text-align: right;">8</td>
<td style="text-align: right;">8</td>
<td style="text-align: right;">0.72</td>
<td style="text-align: left;">4 Likely</td>
<td style="text-align: left;">3 Significant</td>
<td style="text-align: left;">High (12)</td>
</tr>
<tr class="even">
<td style="text-align: left;">H4</td>
<td style="text-align: left;">Pedestrian / accessibility obstruction</td>
<td style="text-align: right;">4</td>
<td style="text-align: right;">4</td>
<td style="text-align: right;">0.49</td>
<td style="text-align: left;">3 Moderate</td>
<td style="text-align: left;">3 Significant</td>
<td style="text-align: left;">Medium (9)</td>
</tr>
<tr class="odd">
<td style="text-align: left;">H5</td>
<td style="text-align: left;">Occupant-related immobilization</td>
<td style="text-align: right;">9</td>
<td style="text-align: right;">3</td>
<td style="text-align: right;">0.41</td>
<td style="text-align: left;">3 Moderate</td>
<td style="text-align: left;">3 Significant</td>
<td style="text-align: left;">Medium (9)</td>
</tr>
<tr class="even">
<td style="text-align: left;">H6</td>
<td style="text-align: left;">Multi-AV clustering / gridlock</td>
<td style="text-align: right;">17</td>
<td style="text-align: right;">10</td>
<td style="text-align: right;">0.8</td>
<td style="text-align: left;">4 Likely</td>
<td style="text-align: left;">3 Significant</td>
<td style="text-align: left;">High (12)</td>
</tr>
<tr class="odd">
<td style="text-align: left;">H7</td>
<td style="text-align: left;">Single-AV traffic obstruction</td>
<td style="text-align: right;">70</td>
<td style="text-align: right;">17</td>
<td style="text-align: right;">0.93</td>
<td style="text-align: left;">5 Almost certain</td>
<td style="text-align: left;">3 Significant</td>
<td style="text-align: left;">Very high (15)</td>
</tr>
</tbody>
</table>
</div>
</figure>
</div>
</section>
<section id="why-each-hazard-sits-where-it-does" class="level2" data-number="7.3">
<h2 data-number="7.3" class="anchored" data-anchor-id="why-each-hazard-sits-where-it-does"><span class="header-section-number">7.3</span> Why each hazard sits where it does</h2>
<ul>
<li><strong>H1 AV-involved collision: Very high.</strong> None of the 6 collisions in the window reported a human injury; one struck a dog. All score <em>Major</em>. Six such events in 184 days give <span class="math inline">\(p\)</span> = 0.63 (Likely), so the cell is Likely × Major.</li>
<li><strong>H2 Emergency-response obstruction: Very high.</strong> Six obstructions, of which 3 occurred during life-threatening incidents: a working fire with people trapped, a garage fire, and a shots-fired investigation. The life-threatening tier alone has <span class="math inline">\(p\)</span> = 0.41 (Moderate × Severe). The Likely × Major cell from all six ranks the same (<em>Very high</em>), so the tie goes to the higher impact. A February incident (a medic delayed to an unconscious patient) is also Severe but lies outside the covered window.</li>
<li><strong>H3 Transit / rail obstruction: High.</strong> All eight are <em>Significant</em> by rubric, with <span class="math inline">\(p\)</span> = 0.72: Likely × Significant.</li>
<li><strong>H4 Pedestrian / accessibility: Medium.</strong> Four events, <span class="math inline">\(p\)</span> = 0.49: Moderate × Significant.</li>
<li><strong>H5 Occupant-related: Medium.</strong> Most are <em>Minor</em> (an asleep rider, a door left open). 3 reach <em>Significant</em>: an unconscious rider, an occupant texting 911, and a door-left-open blockage lasting over an hour. That gives Moderate × Significant.</li>
<li><strong>H6 Multi-AV gridlock: High.</strong> 10 of 17 clusters were <em>Significant</em> (5+ AVs or 60+ minutes), giving <span class="math inline">\(p\)</span> = 0.8: Likely × Significant.</li>
<li><strong>H7 Single-AV obstruction: Very high.</strong> Individually mundane: no single-AV incident did worse than delay traffic. But 17 of them lasted an hour or more, about one every 11 days, so a <em>Significant</em> blockage is Almost certain within any 30-day window. This rating depends on the rubric’s 60-minute cutoff for <em>Significant</em>. At a 90-minute or higher cutoff, H7 is <em>High</em> (<a href="#sec-sensitivity" class="quarto-xref">Section&nbsp;8</a>).</li>
</ul>
<p><strong>Two kinds of red.</strong> H1, H2, and H7 share the <em>Very high</em> band for different reasons. H1 and H2 are <strong>consequence-driven</strong>: they occur about monthly, but each can injure someone or delay emergency care, so they are <em>safety</em> problems. H7 is <strong>volume-driven</strong>: its worst outcome is a traffic delay, but it happens so often that the delay is a near-certainty, so it is an <em>operational</em> problem whose lever is faster recovery. A risk matrix collapses frequency and consequence into one color, and is known to blur exactly this distinction <span class="citation" data-cites="cox2008">(<a href="#ref-cox2008" role="doc-biblioref">Cox 2008</a>)</span>. Read the H7 rating as “routine and costly”, not “dangerous”.</p>
</section>
</section>
<section id="sec-sensitivity" class="level1" data-number="8">
<h1 data-number="8"><span class="header-section-number">8</span> Sensitivity analysis</h1>
<p><a href="#tbl-sensitivity" class="quarto-xref">Table&nbsp;16</a> re-places every hazard under alternative choices: a plug-in MLE probability, 7- and 90-day horizons, February included (212 exposure days, all 123 incidents), the supplementary incidents added, the conventional “total frequency × 90th-percentile impact” rule, and two alternative <em>labelers</em>: the manual audit and the best pretrained model (embedding similarity). For the labeler columns, impact is re-scored because it depends on the hazard.</p>
<ul>
<li><strong>Robust to data choices.</strong> No placement changes under the MLE basis, when February is included, or when the supplementary incidents are added.</li>
<li><strong>Robust to the labeler.</strong> Labeling hazards with the manual audit instead of the rules gives <em>identical</em> placements, so the matrix does not hinge on rule errors. Labeling with the embedding model moves transit (H3) and pedestrian/accessibility (H4) up one band and H7 down one band. Those are exactly the classes it over-predicts (<a href="#tbl-pretrained-counts" class="quarto-xref">Table&nbsp;7</a>), so this reflects the labeler’s error, not a fragile matrix.</li>
<li><strong>The horizon sets the absolute level.</strong> A 7-day horizon lowers every hazard one or two bands, and a 90-day horizon raises them. Choosing the horizon is a policy decision, not something the data can settle. The <em>ranking</em> is stable: in every column, H2 is at (or tied for) the highest level and H5 at (or tied for) the lowest. H4 is also at or tied for the lowest everywhere except the embedding-label column.</li>
<li><strong>The duration cutoff matters for H7.</strong> H7 is <em>Very high</em> only because the rubric counts a 60-minute blockage as <em>Significant</em> (<a href="#tbl-threshold-sensitivity" class="quarto-xref">Table&nbsp;17</a>). At a cutoff of 90 minutes or more it drops to <em>High</em>, and it stays <em>High</em> even at 180 minutes, because routine 10-minute-plus blockages keep it Almost certain × Minor. No other hazard moves: H1–H5 take their impact from the consequence type, and H6 mostly from clusters of 5+ AVs. We keep 60 minutes as the base case because it was fixed before placement; raising it after seeing the result would tune the rubric to the answer.</li>
<li><strong>The placement rule matters for H2.</strong> The conventional rule puts H2 at <em>Extreme</em>. It pairs H2’s overall frequency (six events) with its rarer life-threatening tier (three events), overstating the probability of the Severe outcome. Avoiding exactly that inconsistency is why the risk-curve method is the base case.</li>
</ul>
<div id="tbl-sensitivity" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-tbl figure">
<figcaption class="quarto-float-caption-top quarto-float-caption quarto-float-tbl" id="tbl-sensitivity-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Table&nbsp;16: Sensitivity of risk-matrix placement (cell shown as probability x impact and level).
</figcaption>
<div aria-describedby="tbl-sensitivity-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<table class="caption-top table">
<colgroup>
<col style="width: 10%">
<col style="width: 16%">
<col style="width: 6%">
<col style="width: 6%">
<col style="width: 7%">
<col style="width: 11%">
<col style="width: 11%">
<col style="width: 10%">
<col style="width: 9%">
<col style="width: 10%">
</colgroup>
<thead>
<tr class="header">
<th style="text-align: left;">Hazard</th>
<th style="text-align: left;">Base (Bayesian, 30 d, covered months)</th>
<th style="text-align: left;">Plug-in MLE</th>
<th style="text-align: left;">7-day horizon</th>
<th style="text-align: left;">90-day horizon</th>
<th style="text-align: left;">Include February (212 d)</th>
<th style="text-align: left;">+ supplementary incidents</th>
<th style="text-align: left;">Total freq x P90 impact</th>
<th style="text-align: left;">Manual audit labels</th>
<th style="text-align: left;">Embedding-model labels</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">H1 Collision</td>
<td style="text-align: left;">4x4 Very high</td>
<td style="text-align: left;">4x4 Very high</td>
<td style="text-align: left;">2x4 Medium</td>
<td style="text-align: left;">5x4 Extreme</td>
<td style="text-align: left;">4x4 Very high</td>
<td style="text-align: left;">4x4 Very high</td>
<td style="text-align: left;">4x4 Very high</td>
<td style="text-align: left;">4x4 Very high</td>
<td style="text-align: left;">4x4 Very high</td>
</tr>
<tr class="even">
<td style="text-align: left;">H2 Emergency obstruction</td>
<td style="text-align: left;">3x5 Very high</td>
<td style="text-align: left;">3x5 Very high</td>
<td style="text-align: left;">2x5 High</td>
<td style="text-align: left;">4x5 Extreme</td>
<td style="text-align: left;">3x5 Very high</td>
<td style="text-align: left;">3x5 Very high</td>
<td style="text-align: left;">4x5 Extreme</td>
<td style="text-align: left;">3x5 Very high</td>
<td style="text-align: left;">3x5 Very high</td>
</tr>
<tr class="odd">
<td style="text-align: left;">H3 Transit obstruction</td>
<td style="text-align: left;">4x3 High</td>
<td style="text-align: left;">4x3 High</td>
<td style="text-align: left;">3x3 Medium</td>
<td style="text-align: left;">5x3 Very high</td>
<td style="text-align: left;">4x3 High</td>
<td style="text-align: left;">4x3 High</td>
<td style="text-align: left;">4x3 High</td>
<td style="text-align: left;">4x3 High</td>
<td style="text-align: left;">5x3 Very high</td>
</tr>
<tr class="even">
<td style="text-align: left;">H4 Ped/accessibility</td>
<td style="text-align: left;">3x3 Medium</td>
<td style="text-align: left;">3x3 Medium</td>
<td style="text-align: left;">2x3 Medium</td>
<td style="text-align: left;">4x3 High</td>
<td style="text-align: left;">3x3 Medium</td>
<td style="text-align: left;">3x3 Medium</td>
<td style="text-align: left;">3x3 Medium</td>
<td style="text-align: left;">3x3 Medium</td>
<td style="text-align: left;">4x3 High</td>
</tr>
<tr class="odd">
<td style="text-align: left;">H5 Occupant-related</td>
<td style="text-align: left;">3x3 Medium</td>
<td style="text-align: left;">3x3 Medium</td>
<td style="text-align: left;">2x3 Medium</td>
<td style="text-align: left;">4x3 High</td>
<td style="text-align: left;">3x3 Medium</td>
<td style="text-align: left;">3x3 Medium</td>
<td style="text-align: left;">4x3 High</td>
<td style="text-align: left;">3x3 Medium</td>
<td style="text-align: left;">3x3 Medium</td>
</tr>
<tr class="even">
<td style="text-align: left;">H6 Multi-AV gridlock</td>
<td style="text-align: left;">4x3 High</td>
<td style="text-align: left;">4x3 High</td>
<td style="text-align: left;">3x3 Medium</td>
<td style="text-align: left;">5x3 Very high</td>
<td style="text-align: left;">4x3 High</td>
<td style="text-align: left;">4x3 High</td>
<td style="text-align: left;">5x3 Very high</td>
<td style="text-align: left;">4x3 High</td>
<td style="text-align: left;">4x3 High</td>
</tr>
<tr class="odd">
<td style="text-align: left;">H7 Single-AV obstruction</td>
<td style="text-align: left;">5x3 Very high</td>
<td style="text-align: left;">5x3 Very high</td>
<td style="text-align: left;">3x3 Medium</td>
<td style="text-align: left;">5x3 Very high</td>
<td style="text-align: left;">5x3 Very high</td>
<td style="text-align: left;">5x3 Very high</td>
<td style="text-align: left;">5x3 Very high</td>
<td style="text-align: left;">5x3 Very high</td>
<td style="text-align: left;">4x3 High</td>
</tr>
</tbody>
</table>
</div>
</figure>
</div>
<div id="tbl-threshold-sensitivity" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-tbl figure">
<figcaption class="quarto-float-caption-top quarto-float-caption quarto-float-tbl" id="tbl-threshold-sensitivity-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Table&nbsp;17: Risk-matrix placement when the duration threshold for a Significant impact is raised (all incidents re-scored; base case 60 minutes).
</figcaption>
<div aria-describedby="tbl-threshold-sensitivity-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<table class="caption-top table">
<colgroup>
<col style="width: 22%">
<col style="width: 19%">
<col style="width: 19%">
<col style="width: 19%">
<col style="width: 19%">
</colgroup>
<thead>
<tr class="header">
<th style="text-align: left;">Hazard</th>
<th style="text-align: left;">Significant at &gt;= 60 min</th>
<th style="text-align: left;">Significant at &gt;= 90 min</th>
<th style="text-align: left;">Significant at &gt;= 120 min</th>
<th style="text-align: left;">Significant at &gt;= 180 min</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">H1 Collision</td>
<td style="text-align: left;">4x4 Very high</td>
<td style="text-align: left;">4x4 Very high</td>
<td style="text-align: left;">4x4 Very high</td>
<td style="text-align: left;">4x4 Very high</td>
</tr>
<tr class="even">
<td style="text-align: left;">H2 Emergency obstruction</td>
<td style="text-align: left;">3x5 Very high</td>
<td style="text-align: left;">3x5 Very high</td>
<td style="text-align: left;">3x5 Very high</td>
<td style="text-align: left;">3x5 Very high</td>
</tr>
<tr class="odd">
<td style="text-align: left;">H3 Transit obstruction</td>
<td style="text-align: left;">4x3 High</td>
<td style="text-align: left;">4x3 High</td>
<td style="text-align: left;">4x3 High</td>
<td style="text-align: left;">4x3 High</td>
</tr>
<tr class="even">
<td style="text-align: left;">H4 Ped/accessibility</td>
<td style="text-align: left;">3x3 Medium</td>
<td style="text-align: left;">3x3 Medium</td>
<td style="text-align: left;">3x3 Medium</td>
<td style="text-align: left;">3x3 Medium</td>
</tr>
<tr class="odd">
<td style="text-align: left;">H5 Occupant-related</td>
<td style="text-align: left;">3x3 Medium</td>
<td style="text-align: left;">3x3 Medium</td>
<td style="text-align: left;">3x3 Medium</td>
<td style="text-align: left;">3x3 Medium</td>
</tr>
<tr class="even">
<td style="text-align: left;">H6 Multi-AV gridlock</td>
<td style="text-align: left;">4x3 High</td>
<td style="text-align: left;">4x3 High</td>
<td style="text-align: left;">4x3 High</td>
<td style="text-align: left;">4x3 High</td>
</tr>
<tr class="odd">
<td style="text-align: left;">H7 Single-AV obstruction</td>
<td style="text-align: left;">5x3 Very high</td>
<td style="text-align: left;">4x3 High</td>
<td style="text-align: left;">4x3 High</td>
<td style="text-align: left;">5x2 High</td>
</tr>
<tr class="even">
<td style="text-align: left;">H7 incidents at/above threshold</td>
<td style="text-align: left;">17</td>
<td style="text-align: left;">11</td>
<td style="text-align: left;">9</td>
<td style="text-align: left;">3</td>
</tr>
</tbody>
</table>
</div>
</figure>
</div>
</section>
<section id="discussion-and-limitations" class="level1" data-number="9">
<h1 data-number="9"><span class="header-section-number">9</span> Discussion and limitations</h1>
<section id="sec-judgment" class="level2" data-number="9.1">
<h2 data-number="9.1" class="anchored" data-anchor-id="sec-judgment"><span class="header-section-number">9.1</span> What is measured and what is judged</h2>
<p>Risk assessment mixes measurement with judgment, and the two deserve different levels of trust.</p>
<p><strong>Measured (reproducible from the data):</strong> incident counts, durations, and AV counts; the Poisson and Bayesian rate estimates and their intervals; every statistical test of change over time; and the classifier and inter-coder agreement scores.</p>
<p><strong>Judged (defensible, but someone else could reasonably choose differently):</strong></p>
<table class="caption-top table">
<colgroup>
<col style="width: 33%">
<col style="width: 33%">
<col style="width: 33%">
</colgroup>
<thead>
<tr class="header">
<th>Judgment</th>
<th>Where it enters</th>
<th>How sensitive the result is</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>The hazard taxonomy and its severity-first precedence</td>
<td>Which hazard each incident counts toward</td>
<td>Low: an independent LLM coder reproduced about 97% of labels from the written definitions</td>
</tr>
<tr class="even">
<td>The impact rubric, e.g.&nbsp;60 minutes = <em>Significant</em>, emergency obstruction = <em>Major</em></td>
<td>The impact axis</td>
<td>High for H7 (<em>Very high</em> at 60 minutes, <em>High</em> at 90+); none for H1–H5</td>
</tr>
<tr class="odd">
<td>The 30-day planning horizon</td>
<td>The probability axis</td>
<td>High for absolute levels (a 7-day horizon lowers every hazard); low for the ranking</td>
</tr>
<tr class="even">
<td>The template’s probability bands and cell colors</td>
<td>Converting numbers into bands</td>
<td>Fixed by the course template, not tuned to this data</td>
</tr>
<tr class="odd">
<td>Risk-curve placement over “total frequency × worst impact”</td>
<td>Pairing probability with impact</td>
<td>Matters for H2 only (<em>Very high</em> vs <em>Extreme</em>)</td>
</tr>
<tr class="even">
<td>Treating February and April–May as coverage gaps</td>
<td>The exposure window</td>
<td>None: including February changes no placement</td>
</tr>
</tbody>
</table>
<p>Every judgment was fixed before the risk matrix was drawn, and each is written down in code (<code>av_blocking.severity</code>, <code>av_blocking.config</code>) so that it can be challenged and re-run. The sensitivity tables show how far each choice moves the result. The colors on the matrix should therefore be read as a structured, transparent <em>opinion</em> built on measured rates, not as a measurement. The rates, intervals, and risk curves reported beside it are the measured part.</p>
</section>
<section id="limitations" class="level2" data-number="9.2">
<h2 data-number="9.2" class="anchored" data-anchor-id="limitations"><span class="header-section-number">9.2</span> Limitations</h2>
<ul>
<li><strong>No exposure denominator.</strong> Rates are per calendar day. If fleet size or vehicle-miles grew during 2025, a flat incident rate would mean a <em>falling</em> per-mile rate. Adding exposure, for example from CPUC quarterly reports, is a one-argument change in <code>av_blocking.frequency</code>.</li>
<li><strong>Under-recording and selection.</strong> The DEM log captures incidents that reached dispatchers. Brief blockages cleared before anyone called are missing, so all frequencies are lower bounds.</li>
<li><strong>Narrative quality.</strong> Truncation limits classification. Truncated incidents fall to the default H7, so the frequencies of H1–H5 are, if anything, <em>under</em>-estimated, especially before August.</li>
<li><strong>Single-analyst labels, partly mitigated.</strong> The taxonomy, rules, and audit labels come from one analyst. A blind LLM second coder agreed closely (<span class="math inline">\(\kappa\)</span> = 0.95), but agreement between language models is weaker evidence than agreement between independent human coders, which remains the gold standard.</li>
<li><strong>Risk matrices are coarse.</strong> Banding discards information and can rank risks inconsistently <span class="citation" data-cites="cox2008">(<a href="#ref-cox2008" role="doc-biblioref">Cox 2008</a>)</span>. We mitigate this by publishing the underlying rates, intervals, and risk curves alongside each cell, and by showing the sensitivity of each placement.</li>
</ul>
</section>
</section>
<section id="conclusions" class="level1" data-number="10">
<h1 data-number="10"><span class="header-section-number">10</span> Conclusions</h1>
<p>Over 184 covered days the DEM log records 120 AV blocking incidents, about 19.6 per 30 days (one every 1.5 days). Neither the incident rate nor incident duration shows a statistically significant trend. On the risk matrix, H1 (AV-involved collision) is <strong>Very high</strong>; H2 (Emergency-response obstruction) is <strong>Very high</strong>; H3 (Transit / rail obstruction) is <strong>High</strong>; H4 (Pedestrian / accessibility obstruction) is <strong>Medium</strong>; H5 (Occupant-related immobilization) is <strong>Medium</strong>; H6 (Multi-AV clustering / gridlock) is <strong>High</strong>; H7 (Single-AV traffic obstruction) is <strong>Very high</strong>.</p>
<p>Three conclusions are well supported by the data:</p>
<ol type="1">
<li><strong>Blocking is routine, not rare.</strong> About 4.6 logged incidents per week, with a median duration of 23 minutes and 28% lasting an hour or more.</li>
<li><strong>The highest risks come from consequence, not volume.</strong> Collisions and emergency-response obstruction occur about monthly but carry Major-to-Severe impacts. The sheer volume of routine single-AV blockages also earns a <em>Very high</em> rating.</li>
<li><strong>There is no statistically detectable trend</strong> in incident rate, duration, or multi-AV share over the covered months. The one apparent change, in hazard mix, coincides with a change in narrative recording.</li>
</ol>
<p>The analysis points to two practical levers. The first is <strong>better data</strong>: untruncated narratives, structured fields for what was obstructed, and fleet exposure. The second is <strong>faster recovery</strong> for long single-AV blockages and for any AV near an emergency scene, where minutes matter most.</p>
</section>
<section id="acknowledgments" class="level1 unnumbered">
<h1 class="unnumbered">Acknowledgments</h1>
<p>The incident data come from the San Francisco Department of Emergency Management. Most of the difficult original cleaning and coding of these records was performed by <strong>Dr.&nbsp;Missy Cummings</strong>; this paper would not be possible without that work. The risk-matrix template (bands, levels, and colors) was provided by the course team.</p>
</section>
<section id="references" class="level1 unnumbered">
<h1 class="unnumbered">References</h1>
<div id="refs" class="references csl-bib-body hanging-indent" data-entry-spacing="0" role="list">
<div id="ref-armitage1955" class="csl-entry" role="listitem">
Armitage, P. 1955. <span>“Tests for Linear Trends in Proportions and Frequencies.”</span> <em>Biometrics</em> 11 (3): 375–86.
</div>
<div id="ref-chen2016" class="csl-entry" role="listitem">
Chen, Tianqi, and Carlos Guestrin. 2016. <span>“<span>XGBoost</span>: A Scalable Tree Boosting System.”</span> In <em>Proceedings of the 22nd ACM SIGKDD International Conference on Knowledge Discovery and Data Mining</em>, 785–94.
</div>
<div id="ref-cohen1960" class="csl-entry" role="listitem">
Cohen, Jacob. 1960. <span>“A Coefficient of Agreement for Nominal Scales.”</span> <em>Educational and Psychological Measurement</em> 20 (1): 37–46.
</div>
<div id="ref-cox2008" class="csl-entry" role="listitem">
Cox, Jr., Louis Anthony. 2008. <span>“What’s Wrong with Risk Matrices?”</span> <em>Risk Analysis</em> 28 (2): 497–512.
</div>
<div id="ref-efron1993" class="csl-entry" role="listitem">
Efron, Bradley, and Robert J. Tibshirani. 1993. <em>An Introduction to the Bootstrap</em>. New York: Chapman &amp; Hall.
</div>
<div id="ref-garwood1936" class="csl-entry" role="listitem">
Garwood, F. 1936. <span>“Fiducial Limits for the <span>Poisson</span> Distribution.”</span> <em>Biometrika</em> 28 (3/4): 437–42.
</div>
<div id="ref-he2023" class="csl-entry" role="listitem">
He, Pengcheng, Jianfeng Gao, and Weizhu Chen. 2023. <span>“<span>DeBERTaV3</span>: Improving <span>DeBERTa</span> Using <span>ELECTRA</span>-Style Pre-Training with Gradient-Disentangled Embedding Sharing.”</span> In <em>The Eleventh International Conference on Learning Representations (ICLR)</em>.
</div>
<div id="ref-jeffreys1946" class="csl-entry" role="listitem">
Jeffreys, Harold. 1946. <span>“An Invariant Form for the Prior Probability in Estimation Problems.”</span> <em>Proceedings of the Royal Society of London. Series A</em> 186 (1007): 453–61.
</div>
<div id="ref-jonckheere1954" class="csl-entry" role="listitem">
Jonckheere, A. R. 1954. <span>“A Distribution-Free k-Sample Test Against Ordered Alternatives.”</span> <em>Biometrika</em> 41 (1/2): 133–45.
</div>
<div id="ref-kendall1975" class="csl-entry" role="listitem">
Kendall, Maurice G. 1975. <em>Rank Correlation Methods</em>. 4th ed. London: Charles Griffin.
</div>
<div id="ref-kruskal1952" class="csl-entry" role="listitem">
Kruskal, William H., and W. Allen Wallis. 1952. <span>“Use of Ranks in One-Criterion Variance Analysis.”</span> <em>Journal of the American Statistical Association</em> 47 (260): 583–621.
</div>
<div id="ref-laurer2024" class="csl-entry" role="listitem">
Laurer, Moritz, Wouter van Atteveldt, Andreu Casas, and Kasper Welbers. 2024. <span>“Less Annotating, More Classifying: Addressing the Data Scarcity Issue of Supervised Machine Learning with Deep Transfer Learning and <span>BERT-NLI</span>.”</span> <em>Political Analysis</em> 32 (1): 84–100.
</div>
<div id="ref-lewis2020" class="csl-entry" role="listitem">
Lewis, Mike, Yinhan Liu, Naman Goyal, Marjan Ghazvininejad, Abdelrahman Mohamed, Omer Levy, Veselin Stoyanov, and Luke Zettlemoyer. 2020. <span>“<span>BART</span>: Denoising Sequence-to-Sequence Pre-Training for Natural Language Generation, Translation, and Comprehension.”</span> In <em>Proceedings of the 58th Annual Meeting of the Association for Computational Linguistics</em>, 7871–80.
</div>
<div id="ref-mann1945" class="csl-entry" role="listitem">
Mann, Henry B. 1945. <span>“Nonparametric Tests Against Trend.”</span> <em>Econometrica</em> 13 (3): 245–59.
</div>
<div id="ref-mann1947" class="csl-entry" role="listitem">
Mann, Henry B., and Donald R. Whitney. 1947. <span>“On a Test of Whether One of Two Random Variables Is Stochastically Larger Than the Other.”</span> <em>The Annals of Mathematical Statistics</em> 18 (1): 50–60.
</div>
<div id="ref-mcnemar1947" class="csl-entry" role="listitem">
McNemar, Quinn. 1947. <span>“Note on the Sampling Error of the Difference Between Correlated Proportions or Percentages.”</span> <em>Psychometrika</em> 12 (2): 153–57.
</div>
<div id="ref-mxbai2024" class="csl-entry" role="listitem">
Mixedbread AI. 2024. <span>“Mxbai-Embed-Large-V1.”</span> <a href="https://huggingface.co/mixedbread-ai/mxbai-embed-large-v1" class="uri">https://huggingface.co/mixedbread-ai/mxbai-embed-large-v1</a>.
</div>
<div id="ref-reimers2019" class="csl-entry" role="listitem">
Reimers, Nils, and Iryna Gurevych. 2019. <span>“Sentence-<span>BERT</span>: Sentence Embeddings Using <span>Siamese</span> <span>BERT</span>-Networks.”</span> In <em>Proceedings of the 2019 Conference on Empirical Methods in Natural Language Processing (EMNLP-IJCNLP)</em>, 3982–92.
</div>
<div id="ref-sen1968" class="csl-entry" role="listitem">
Sen, Pranab Kumar. 1968. <span>“Estimates of the Regression Coefficient Based on <span class="nocase">Kendall’s</span> Tau.”</span> <em>Journal of the American Statistical Association</em> 63 (324): 1379–89.
</div>
<div id="ref-shapiro1965" class="csl-entry" role="listitem">
Shapiro, S. S., and M. B. Wilk. 1965. <span>“An Analysis of Variance Test for Normality (Complete Samples).”</span> <em>Biometrika</em> 52 (3/4): 591–611.
</div>
<div id="ref-yin2019" class="csl-entry" role="listitem">
Yin, Wenpeng, Jamaal Hay, and Dan Roth. 2019. <span>“Benchmarking Zero-Shot Text Classification: Datasets, Evaluation and Entailment Approach.”</span> In <em>Proceedings of the 2019 Conference on Empirical Methods in Natural Language Processing (EMNLP-IJCNLP)</em>, 3914–23.
</div>
</div>


</section>

</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
  window.document.addEventListener("DOMContentLoaded", function (event) {
    const icon = "";
    const anchorJS = new window.AnchorJS();
    anchorJS.options = {
      placement: 'right',
      icon: icon
    };
    anchorJS.add('.anchored');
    const isCodeAnnotation = (el) => {
      for (const clz of el.classList) {
        if (clz.startsWith('code-annotation-')) {                     
          return true;
        }
      }
      return false;
    }
    const onCopySuccess = function(e) {
      // button target
      const button = e.trigger;
      // don't keep focus
      button.blur();
      // flash "checked"
      button.classList.add('code-copy-button-checked');
      var currentTitle = button.getAttribute("title");
      button.setAttribute("title", "Copied!");
      let tooltip;
      if (window.bootstrap) {
        button.setAttribute("data-bs-toggle", "tooltip");
        button.setAttribute("data-bs-placement", "left");
        button.setAttribute("data-bs-title", "Copied!");
        tooltip = new bootstrap.Tooltip(button, 
          { trigger: "manual", 
            customClass: "code-copy-button-tooltip",
            offset: [0, -8]});
        tooltip.show();    
      }
      setTimeout(function() {
        if (tooltip) {
          tooltip.hide();
          button.removeAttribute("data-bs-title");
          button.removeAttribute("data-bs-toggle");
          button.removeAttribute("data-bs-placement");
        }
        button.setAttribute("title", currentTitle);
        button.classList.remove('code-copy-button-checked');
      }, 1000);
      // clear code selection
      e.clearSelection();
    }
    const getTextToCopy = function(trigger) {
      const outerScaffold = trigger.parentElement.cloneNode(true);
      const codeEl = outerScaffold.querySelector('code');
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
    const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
      text: getTextToCopy
    });
    clipboard.on('success', onCopySuccess);
    if (window.document.getElementById('quarto-embedded-source-code-modal')) {
      const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
        text: getTextToCopy,
        container: window.document.getElementById('quarto-embedded-source-code-modal')
      });
      clipboardModal.on('success', onCopySuccess);
    }
      var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
      var mailtoRegex = new RegExp(/^mailto:/);
        var filterRegex = new RegExp("https:\/\/jonathanwilsonami\.github\.io\/av-blocking-analysis\/");
      var isInternal = (href) => {
          return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
      }
      // Inspect non-navigation links and adorn them if external
     var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
      for (var i=0; i<links.length; i++) {
        const link = links[i];
        if (!isInternal(link.href)) {
          // undo the damage that might have been done by quarto-nav.js in the case of
          // links that we want to consider external
          if (link.dataset.originalHref !== undefined) {
            link.href = link.dataset.originalHref;
          }
        }
      }
    function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
      const config = {
        allowHTML: true,
        maxWidth: 500,
        delay: 100,
        arrow: false,
        appendTo: function(el) {
            return el.parentElement;
        },
        interactive: true,
        interactiveBorder: 10,
        theme: 'quarto',
        placement: 'bottom-start',
      };
      if (contentFn) {
        config.content = contentFn;
      }
      if (onTriggerFn) {
        config.onTrigger = onTriggerFn;
      }
      if (onUntriggerFn) {
        config.onUntrigger = onUntriggerFn;
      }
      window.tippy(el, config); 
    }
    const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
    for (var i=0; i<noterefs.length; i++) {
      const ref = noterefs[i];
      tippyHover(ref, function() {
        // use id or data attribute instead here
        let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
        try { href = new URL(href).hash; } catch {}
        const id = href.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note) {
          return note.innerHTML;
        } else {
          return "";
        }
      });
    }
    const xrefs = window.document.querySelectorAll('a.quarto-xref');
    const processXRef = (id, note) => {
      // Strip column container classes
      const stripColumnClz = (el) => {
        el.classList.remove("page-full", "page-columns");
        if (el.children) {
          for (const child of el.children) {
            stripColumnClz(child);
          }
        }
      }
      stripColumnClz(note)
      if (id === null || id.startsWith('sec-')) {
        // Special case sections, only their first couple elements
        const container = document.createElement("div");
        if (note.children && note.children.length > 2) {
          container.appendChild(note.children[0].cloneNode(true));
          for (let i = 1; i < note.children.length; i++) {
            const child = note.children[i];
            if (child.tagName === "P" && child.innerText === "") {
              continue;
            } else {
              container.appendChild(child.cloneNode(true));
              break;
            }
          }
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(container);
          }
          return container.innerHTML
        } else {
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(note);
          }
          return note.innerHTML;
        }
      } else {
        // Remove any anchor links if they are present
        const anchorLink = note.querySelector('a.anchorjs-link');
        if (anchorLink) {
          anchorLink.remove();
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        if (note.classList.contains("callout")) {
          return note.outerHTML;
        } else {
          return note.innerHTML;
        }
      }
    }
    for (var i=0; i<xrefs.length; i++) {
      const xref = xrefs[i];
      tippyHover(xref, undefined, function(instance) {
        instance.disable();
        let url = xref.getAttribute('href');
        let hash = undefined; 
        if (url.startsWith('#')) {
          hash = url;
        } else {
          try { hash = new URL(url).hash; } catch {}
        }
        if (hash) {
          const id = hash.replace(/^#\/?/, "");
          const note = window.document.getElementById(id);
          if (note !== null) {
            try {
              const html = processXRef(id, note.cloneNode(true));
              instance.setContent(html);
            } finally {
              instance.enable();
              instance.show();
            }
          } else {
            // See if we can fetch this
            fetch(url.split('#')[0])
            .then(res => res.text())
            .then(html => {
              const parser = new DOMParser();
              const htmlDoc = parser.parseFromString(html, "text/html");
              const note = htmlDoc.getElementById(id);
              if (note !== null) {
                const html = processXRef(id, note);
                instance.setContent(html);
              } 
            }).finally(() => {
              instance.enable();
              instance.show();
            });
          }
        } else {
          // See if we can fetch a full url (with no hash to target)
          // This is a special case and we should probably do some content thinning / targeting
          fetch(url)
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.querySelector('main.content');
            if (note !== null) {
              // This should only happen for chapter cross references
              // (since there is no id in the URL)
              // remove the first header
              if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
                note.children[0].remove();
              }
              const html = processXRef(null, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      }, function(instance) {
      });
    }
        let selectedAnnoteEl;
        const selectorForAnnotation = ( cell, annotation) => {
          let cellAttr = 'data-code-cell="' + cell + '"';
          let lineAttr = 'data-code-annotation="' +  annotation + '"';
          const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
          return selector;
        }
        const selectCodeLines = (annoteEl) => {
          const doc = window.document;
          const targetCell = annoteEl.getAttribute("data-target-cell");
          const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
          const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
          const lines = annoteSpan.getAttribute("data-code-lines").split(",");
          const lineIds = lines.map((line) => {
            return targetCell + "-" + line;
          })
          let top = null;
          let height = null;
          let parent = null;
          if (lineIds.length > 0) {
              //compute the position of the single el (top and bottom and make a div)
              const el = window.document.getElementById(lineIds[0]);
              top = el.offsetTop;
              height = el.offsetHeight;
              parent = el.parentElement.parentElement;
            if (lineIds.length > 1) {
              const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
              const bottom = lastEl.offsetTop + lastEl.offsetHeight;
              height = bottom - top;
            }
            if (top !== null && height !== null && parent !== null) {
              // cook up a div (if necessary) and position it 
              let div = window.document.getElementById("code-annotation-line-highlight");
              if (div === null) {
                div = window.document.createElement("div");
                div.setAttribute("id", "code-annotation-line-highlight");
                div.style.position = 'absolute';
                parent.appendChild(div);
              }
              div.style.top = top - 2 + "px";
              div.style.height = height + 4 + "px";
              div.style.left = 0;
              let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
              if (gutterDiv === null) {
                gutterDiv = window.document.createElement("div");
                gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
                gutterDiv.style.position = 'absolute';
                const codeCell = window.document.getElementById(targetCell);
                const gutter = codeCell.querySelector('.code-annotation-gutter');
                gutter.appendChild(gutterDiv);
              }
              gutterDiv.style.top = top - 2 + "px";
              gutterDiv.style.height = height + 4 + "px";
            }
            selectedAnnoteEl = annoteEl;
          }
        };
        const unselectCodeLines = () => {
          const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
          elementsIds.forEach((elId) => {
            const div = window.document.getElementById(elId);
            if (div) {
              div.remove();
            }
          });
          selectedAnnoteEl = undefined;
        };
          // Handle positioning of the toggle
      window.addEventListener(
        "resize",
        throttle(() => {
          elRect = undefined;
          if (selectedAnnoteEl) {
            selectCodeLines(selectedAnnoteEl);
          }
        }, 10)
      );
      function throttle(fn, ms) {
      let throttle = false;
      let timer;
        return (...args) => {
          if(!throttle) { // first call gets through
              fn.apply(this, args);
              throttle = true;
          } else { // all the others get throttled
              if(timer) clearTimeout(timer); // cancel #2
              timer = setTimeout(() => {
                fn.apply(this, args);
                timer = throttle = false;
              }, ms);
          }
        };
      }
        // Attach click handler to the DT
        const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
        for (const annoteDlNode of annoteDls) {
          annoteDlNode.addEventListener('click', (event) => {
            const clickedEl = event.target;
            if (clickedEl !== selectedAnnoteEl) {
              unselectCodeLines();
              const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
              if (activeEl) {
                activeEl.classList.remove('code-annotation-active');
              }
              selectCodeLines(clickedEl);
              clickedEl.classList.add('code-annotation-active');
            } else {
              // Unselect the line
              unselectCodeLines();
              clickedEl.classList.remove('code-annotation-active');
            }
          });
        }
    const findCites = (el) => {
      const parentEl = el.parentElement;
      if (parentEl) {
        const cites = parentEl.dataset.cites;
        if (cites) {
          return {
            el,
            cites: cites.split(' ')
          };
        } else {
          return findCites(el.parentElement)
        }
      } else {
        return undefined;
      }
    };
    var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
    for (var i=0; i<bibliorefs.length; i++) {
      const ref = bibliorefs[i];
      const citeInfo = findCites(ref);
      if (citeInfo) {
        tippyHover(citeInfo.el, function() {
          var popup = window.document.createElement('div');
          citeInfo.cites.forEach(function(cite) {
            var citeDiv = window.document.createElement('div');
            citeDiv.classList.add('hanging-indent');
            citeDiv.classList.add('csl-entry');
            var biblioDiv = window.document.getElementById('ref-' + cite);
            if (biblioDiv) {
              citeDiv.innerHTML = biblioDiv.innerHTML;
            }
            popup.appendChild(citeDiv);
          });
          return popup.innerHTML;
        });
      }
    }
  });
  </script>
</div> <!-- /content -->
<footer class="footer">
  <div class="nav-footer">
    <div class="nav-footer-left">
      &nbsp;
    </div>   
    <div class="nav-footer-center">
<p>Data: San Francisco Department of Emergency Management, original cleaning by Dr.&nbsp;Missy Cummings.</p>
<div class="toc-actions d-sm-block d-md-none"><ul><li><a href="https://github.com/jonathanwilsonami/av-blocking-analysis/blob/main/paper.qmd" class="toc-action"><i class="bi bi-github"></i>View source</a></li><li><a href="https://github.com/jonathanwilsonami/av-blocking-analysis/issues/new" class="toc-action"><i class="bi empty"></i>Report an issue</a></li></ul></div></div>
    <div class="nav-footer-right">
      &nbsp;
    </div>
  </div>
</footer>




</body></html>